import { std } from "tswow-stdlib"
import { MODNAME } from "../../modname"



export let HeavenlyPurpose = std.Items.create(MODNAME,'heavenlypurpose',33203)
HeavenlyPurpose.Quality.setBlue()
HeavenlyPurpose.RequiredLevel.set(5)
HeavenlyPurpose.Socket.clearAll()
export let PrimalFury = std.Items.create(MODNAME,'primalfury',33206)
PrimalFury.Quality.setBlue()
PrimalFury.RequiredLevel.set(5)
PrimalFury.Socket.clearAll()
export let Introspection = std.Items.create(MODNAME,'introspection',33327)
Introspection.Quality.setBlue()
Introspection.RequiredLevel.set(5)
Introspection.Socket.clearAll()
export let FuryOffhand = std.Items.create(MODNAME,'furyoffhand',33640)
FuryOffhand.Quality.setBlue()
FuryOffhand.RequiredLevel.set(5)
FuryOffhand.Socket.clearAll()
export let NaturalRegenHelm = std.Items.create(MODNAME,'nrh',33356)
NaturalRegenHelm.Quality.setBlue()
NaturalRegenHelm.RequiredLevel.set(5)
NaturalRegenHelm.Socket.clearAll()
export let Mojoshield = std.Items.create(MODNAME,'mjs',33332)
Mojoshield.Quality.setBlue()
Mojoshield.RequiredLevel.set(5)
Mojoshield.Socket.clearAll()
export let Bulwarkshield = std.Items.create(MODNAME,'bws',33326)
Bulwarkshield.Quality.setBlue()
Bulwarkshield.RequiredLevel.set(5)
Bulwarkshield.Socket.clearAll()
export let Advocate = std.Items.create(MODNAME,'adv',33299)
Advocate.Quality.setBlue()
Advocate.RequiredLevel.set(5)
Advocate.Socket.clearAll()
export let Avalanche = std.Items.create(MODNAME,'aval',33599)
Avalanche.Quality.setBlue()
Avalanche.RequiredLevel.set(5)
Avalanche.Socket.clearAll()
export let DancingBlades = std.Items.create(MODNAME,'aval',33300)
DancingBlades.Quality.setBlue()
DancingBlades.RequiredLevel.set(5)
DancingBlades.Socket.clearAll()
export let rohk = std.Items.create(MODNAME,'rohk',33478)
rohk.Quality.setBlue()
rohk.RequiredLevel.set(5)
rohk.Socket.clearAll()
export let Crusher = std.Items.create(MODNAME,'crusher',19918)
Crusher.Quality.setBlue()
Crusher.RequiredLevel.set(5)
Crusher.Socket.clearAll()
export let Eyepatch = std.Items.create(MODNAME,'eyepatch',19945)
Eyepatch.Quality.setBlue()
Eyepatch.RequiredLevel.set(5)
Eyepatch.Socket.clearAll()
export let Medivh01 = std.Items.create(MODNAME,'medivh01',22632)
Medivh01.Quality.setBlue()
Medivh01.RequiredLevel.set(5)
Medivh01.Socket.clearAll()
export let Medivh02 = std.Items.create(MODNAME,'medivh02',22589)
Medivh02.Quality.setBlue()
Medivh02.RequiredLevel.set(5)
Medivh02.Socket.clearAll()
export let Medivh03 = std.Items.create(MODNAME,'medivh03',22631)
Medivh03.Quality.setBlue()
Medivh03.RequiredLevel.set(5)
Medivh03.Socket.clearAll()
export let Medivh04 = std.Items.create(MODNAME,'medivh04',22630)
Medivh04.Quality.setBlue()
Medivh04.RequiredLevel.set(5)
Medivh04.Socket.clearAll()
export let Valanyr = std.Items.create(MODNAME,'valanyrmace',46017)
Valanyr.Quality.setBlue()
Valanyr.RequiredLevel.set(5)
Valanyr.Socket.clearAll()
