import { MODNAME } from "quests-mod"
import { std } from "../../../../tswow-stdlib/datascripts/build/tswow-stdlib-data"

export let ZandalarVindicatorBreastplate = std.Items.create(MODNAME,'zandalarvindicatorbreastplate',19822)
ZandalarVindicatorBreastplate.Quality.setBlue()
export let ZandalarVindicatorBelt = std.Items.create(MODNAME,'zandalarvindicatorbelt',19823)
ZandalarVindicatorBelt.Quality.setBlue()
export let ZandalarVindicatorArmguards = std.Items.create(MODNAME,'zandalarvindicatorarmguards',19824)
ZandalarVindicatorArmguards.Quality.setBlue()
export let ZandalarFreethinkerBreastplate = std.Items.create(MODNAME,'zandalarfreethinkerbreastplate',19825)
ZandalarFreethinkerBreastplate.Quality.setBlue()
export let ZandalarFreethinkerBelt = std.Items.create(MODNAME,'zandalarfreethinkerbelt',19826)
ZandalarFreethinkerBelt.Quality.setBlue()
export let ZandalarFreethinkerArmguards = std.Items.create(MODNAME,'zandalarfreethinkerarmguards',19827)
ZandalarFreethinkerArmguards.Quality.setBlue()
export let ZandalarAugurHauberk = std.Items.create(MODNAME,'zandalaraugurHauberk',19828)
ZandalarAugurHauberk.Quality.setBlue()
export let ZandalarAugurBelt = std.Items.create(MODNAME,'zandalaraugurbelt',19829)
ZandalarAugurBelt.Quality.setBlue()
export let ZandalarAugurBracers = std.Items.create(MODNAME,'zandalaraugurbracers',19830)
ZandalarAugurBracers.Quality.setBlue()
export let ZandalarPredatorMantle = std.Items.create(MODNAME,'zandalarpredatormantle',19831)
ZandalarPredatorMantle.Quality.setBlue()
export let ZandalarPredatorBelt = std.Items.create(MODNAME,'zandalarpredatorbelt',19832)
ZandalarPredatorBelt.Quality.setBlue()
export let ZandalarPredatorBracers = std.Items.create(MODNAME,'zandalarpredatorbracers',19833)
ZandalarPredatorBracers.Quality.setBlue()
export let ZandalarMadcapTunic = std.Items.create(MODNAME,'zandalarmadcaptunic',19834)
ZandalarMadcapTunic.Quality.setBlue()
export let ZandalarMadcapMantle = std.Items.create(MODNAME,'zandalarmadcapmantle',19835)
ZandalarMadcapMantle.Quality.setBlue()
export let ZandalarMadcapBracers = std.Items.create(MODNAME,'zandalarmadcapbracers',19836)
ZandalarMadcapBracers.Quality.setBlue()
export let ZandalarHaruspexTunic = std.Items.create(MODNAME,'zandalarharuspextunic',19838)
ZandalarHaruspexTunic.Quality.setBlue()
export let ZandalarHaruspexBelt = std.Items.create(MODNAME,'zandalarharuspexbelt',19839)
ZandalarHaruspexBelt.Quality.setBlue()
export let ZandalarHaruspexBracers = std.Items.create(MODNAME,'zandalarharuspexbracers',19840)
ZandalarHaruspexBracers.Quality.setBlue()
export let ZandalarConfessorMantle = std.Items.create(MODNAME,'zandalarconfessormantle',19841)
ZandalarConfessorMantle.Quality.setBlue()
export let ZandalarConfessorBindings = std.Items.create(MODNAME,'zandalarconfessorbindings',19842)
ZandalarConfessorBindings.Quality.setBlue()
export let ZandalarConfessorWraps = std.Items.create(MODNAME,'zandalarconfessorwraps',19843)
ZandalarConfessorWraps.Quality.setBlue()
export let ZandalarIllusionistMantle = std.Items.create(MODNAME,'zandalarillusionistmantle',19845)
ZandalarIllusionistMantle.Quality.setBlue()
export let ZandalarIllusionistWraps = std.Items.create(MODNAME,'zandalarillusionistwraps',19846)
ZandalarIllusionistWraps.Quality.setBlue()
export let ZandalarDemoniacWraps = std.Items.create(MODNAME,'zandalardemoniacwraps',19848)
ZandalarDemoniacWraps.Quality.setBlue()
export let ZandalarDemoniacMantle = std.Items.create(MODNAME,'zandalardemoniacmantle',19849)
ZandalarDemoniacMantle.Quality.setBlue()
export let ZandalarHonorToken = std.Items.create(MODNAME,'zandalarhonortoken',19858)
ZandalarHonorToken.Quality.setBlue()
export let ZandalarianHeroBadge = std.Items.create(MODNAME,'zandalarianherobadge',19948)
ZandalarianHeroBadge.Quality.setBlue()
export let ZandalarianHeroMedallion = std.Items.create(MODNAME,'zandalarianheromedallion',19949)
ZandalarianHeroMedallion.Quality.setBlue()
export let ZandalarianHeroCharm = std.Items.create(MODNAME,'zandalarianherocharm',19950)
ZandalarianHeroCharm.Quality.setBlue()
export let ZandalarDemoniacRobe = std.Items.create(MODNAME,'zandalardemoniacrobe',20033)
ZandalarDemoniacRobe.Quality.setBlue()
export let ZandalarIllusionistRobe = std.Items.create(MODNAME,'zandalarillusionistrobe',20034)
ZandalarIllusionistRobe.Quality.setBlue()
export let ZandalarSignetofMojo = std.Items.create(MODNAME,'zandalarsignetofmojo',20076)
ZandalarSignetofMojo.Quality.setBlue()
export let ZandalarSignetofMight = std.Items.create(MODNAME,'zandalarsignetofmight',20077)
ZandalarSignetofMight.Quality.setBlue()
export let ZandalarSignetofSerenity = std.Items.create(MODNAME,'zandalarsignetofserenity',20078)
ZandalarSignetofSerenity.Quality.setBlue()
export let GrileksCharmofMight = std.Items.create(MODNAME,'grilekscharmofmight',19951)
GrileksCharmofMight.Quality.setBlue()
export let GrileksCharmofValor = std.Items.create(MODNAME,'grilekscharmofnalor',19952)
GrileksCharmofValor.Quality.setBlue()
export let RenatakisCharmofBeasts = std.Items.create(MODNAME,'renatakischarmofbeasts',19953)
RenatakisCharmofBeasts.Quality.setBlue()
export let RenatakisCharmofTrickery = std.Items.create(MODNAME,'renatakischarmoftrickery',19954)
RenatakisCharmofTrickery.Quality.setBlue()
export let WushoolaysCharmofNature = std.Items.create(MODNAME,'wushoolayscharmofnature',19955)
WushoolaysCharmofNature.Quality.setBlue()
export let WushoolaysCharmofSpirits = std.Items.create(MODNAME,'wushoolayscharmofspirits',19956)
WushoolaysCharmofSpirits.Quality.setBlue()
export let HazzarahsCharmofDestruction = std.Items.create(MODNAME,'hazzarahscharmofdestruction',19957)
HazzarahsCharmofDestruction.Quality.setBlue()
export let HazzarahsCharmofHealing = std.Items.create(MODNAME,'hazzarahscharmofhealing',19958)
HazzarahsCharmofHealing.Quality.setBlue()
export let HazzarahsCharmofMagic = std.Items.create(MODNAME,'hazzarahscharmofmagic',19959)
HazzarahsCharmofMagic.Quality.setBlue()
export let PristineEnchantedSouthSeasKelp = std.Items.create(MODNAME,'pristineenchantedsouthseaskelp',19613)
PristineEnchantedSouthSeasKelp.Quality.setBlue()
export let JewelofKajaro = std.Items.create(MODNAME,'jewelofkajaro',19601)
JewelofKajaro.Quality.setBlue()
export let MaelstromsWrath = std.Items.create(MODNAME,'maelstromswrath',19621)
MaelstromsWrath.Quality.setBlue()
export let HerosBrand = std.Items.create(MODNAME,'herosBrand',19588)
HerosBrand.Quality.setBlue()
export let TheAllSeeingEyeofZuldazar = std.Items.create(MODNAME,'theallseeingeyeofzuldazar',19594)
TheAllSeeingEyeofZuldazar.Quality.setBlue()
export let UnmarredVisionofVoodress = std.Items.create(MODNAME,'unmarredvisionofvoodress',19609)
UnmarredVisionofVoodress.Quality.setBlue()
export let ZandalarianShadowMasteryTalisman = std.Items.create(MODNAME,'zandalarianshadowmasterytalisman',19617)
ZandalarianShadowMasteryTalisman.Quality.setBlue()
export let KezansUnstoppableTaint = std.Items.create(MODNAME,'kezansunstoppabletaint',19605)
KezansUnstoppableTaint.Quality.setBlue()
export let RageofMugamba = std.Items.create(MODNAME,'rageofmugamba',19577)
RageofMugamba.Quality.setBlue()
