import { MODNAME } from "quests-mod"
import { std } from "tswow-stdlib"

export let MassiveRedPouch = std.Items.create(MODNAME,'massiveredpouch',805)
MassiveRedPouch.Quality.setBlue()
MassiveRedPouch.ContainerSlots.set(22)
export let MassiveBluePouch = std.Items.create(MODNAME,'massivebluepouch',828)
MassiveBluePouch.Quality.setBlue()
MassiveBluePouch.ContainerSlots.set(22)
export let MassiveBlackPouch = std.Items.create(MODNAME,'massiveblackpouch',5571)
MassiveBlackPouch.Quality.setBlue()
MassiveBlackPouch.ContainerSlots.set(22)
export let MassiveGreenPouch = std.Items.create(MODNAME,'massivegreenpouch',5572)
MassiveGreenPouch.Quality.setBlue()
MassiveGreenPouch.ContainerSlots.set(22)

export let ZandalarVindicatorBreastplate = std.Items.create(MODNAME,'zandalarvindicatorbreastplate',19822)
ZandalarVindicatorBreastplate.Quality.setBlue()
export let ZandalarVindicatorBelt = std.Items.create(MODNAME,'zandalarvindicatorbelt',19823)
ZandalarVindicatorBelt.Quality.setBlue()
export let ZandalarVindicatorArmguards = std.Items.create(MODNAME,'zandalarvindicatorarmguards',19824)
ZandalarVindicatorArmguards.Quality.setBlue()
export let ZandalarFreethinkerBreastplate = std.Items.create(MODNAME,'zandalarfreethinkerbreastplate',19825)
ZandalarFreethinkerBreastplate.Quality.setBlue()
export let ZandalarFreethinkerBelt = std.Items.create(MODNAME,'zandalarfreethinkerbelt',19826)
ZandalarFreethinkerBelt.Quality.setBlue()
export let ZandalarFreethinkerArmguards = std.Items.create(MODNAME,'zandalarfreethinkerarmguards',19827)
ZandalarFreethinkerArmguards.Quality.setBlue()
export let ZandalarAugurHauberk = std.Items.create(MODNAME,'zandalaraugurHauberk',19828)
ZandalarAugurHauberk.Quality.setBlue()
export let ZandalarAugurBelt = std.Items.create(MODNAME,'zandalaraugurbelt',19829)
ZandalarAugurBelt.Quality.setBlue()
export let ZandalarAugurBracers = std.Items.create(MODNAME,'zandalaraugurbracers',19830)
ZandalarAugurBracers.Quality.setBlue()
export let ZandalarPredatorMantle = std.Items.create(MODNAME,'zandalarpredatormantle',19831)
ZandalarPredatorMantle.Quality.setBlue()
export let ZandalarPredatorBelt = std.Items.create(MODNAME,'zandalarpredatorbelt',19832)
ZandalarPredatorBelt.Quality.setBlue()
export let ZandalarPredatorBracers = std.Items.create(MODNAME,'zandalarpredatorbracers',19833)
ZandalarPredatorBracers.Quality.setBlue()
export let ZandalarMadcapTunic = std.Items.create(MODNAME,'zandalarmadcaptunic',19834)
ZandalarMadcapTunic.Quality.setBlue()
export let ZandalarMadcapMantle = std.Items.create(MODNAME,'zandalarmadcapmantle',19835)
ZandalarMadcapMantle.Quality.setBlue()
export let ZandalarMadcapBracers = std.Items.create(MODNAME,'zandalarmadcapbracers',19836)
ZandalarMadcapBracers.Quality.setBlue()
export let ZandalarHaruspexTunic = std.Items.create(MODNAME,'zandalarharuspextunic',19838)
ZandalarHaruspexTunic.Quality.setBlue()
export let ZandalarHaruspexBelt = std.Items.create(MODNAME,'zandalarharuspexbelt',19839)
ZandalarHaruspexBelt.Quality.setBlue()
export let ZandalarHaruspexBracers = std.Items.create(MODNAME,'zandalarharuspexbracers',19840)
ZandalarHaruspexBracers.Quality.setBlue()
export let ZandalarConfessorMantle = std.Items.create(MODNAME,'zandalarconfessormantle',19841)
ZandalarConfessorMantle.Quality.setBlue()
export let ZandalarConfessorBindings = std.Items.create(MODNAME,'zandalarconfessorbindings',19842)
ZandalarConfessorBindings.Quality.setBlue()
export let ZandalarConfessorWraps = std.Items.create(MODNAME,'zandalarconfessorwraps',19843)
ZandalarConfessorWraps.Quality.setBlue()
export let ZandalarIllusionistMantle = std.Items.create(MODNAME,'zandalarillusionistmantle',19845)
ZandalarIllusionistMantle.Quality.setBlue()
export let ZandalarIllusionistWraps = std.Items.create(MODNAME,'zandalarillusionistwraps',19846)
ZandalarIllusionistWraps.Quality.setBlue()
export let ZandalarDemoniacWraps = std.Items.create(MODNAME,'zandalardemoniacwraps',19848)
ZandalarDemoniacWraps.Quality.setBlue()
export let ZandalarDemoniacMantle = std.Items.create(MODNAME,'zandalardemoniacmantle',19849)
ZandalarDemoniacMantle.Quality.setBlue()
export let ZandalarHonorToken = std.Items.create(MODNAME,'zandalarhonortoken',19858)
ZandalarHonorToken.Quality.setBlue()
export let ZandalarianHeroBadge = std.Items.create(MODNAME,'zandalarianherobadge',19948)
ZandalarianHeroBadge.Quality.setBlue()
export let ZandalarianHeroMedallion = std.Items.create(MODNAME,'zandalarianheromedallion',19949)
ZandalarianHeroMedallion.Quality.setBlue()
export let ZandalarianHeroCharm = std.Items.create(MODNAME,'zandalarianherocharm',19950)
ZandalarianHeroCharm.Quality.setBlue()
export let ZandalarDemoniacRobe = std.Items.create(MODNAME,'zandalardemoniacrobe',20033)
ZandalarDemoniacRobe.Quality.setBlue()
export let ZandalarIllusionistRobe = std.Items.create(MODNAME,'zandalarillusionistrobe',20034)
ZandalarIllusionistRobe.Quality.setBlue()
export let ZandalarSignetofMojo = std.Items.create(MODNAME,'zandalarsignetofmojo',20076)
ZandalarSignetofMojo.Quality.setBlue()
export let ZandalarSignetofMight = std.Items.create(MODNAME,'zandalarsignetofmight',20077)
ZandalarSignetofMight.Quality.setBlue()
export let ZandalarSignetofSerenity = std.Items.create(MODNAME,'zandalarsignetofserenity',20078)
ZandalarSignetofSerenity.Quality.setBlue()
export let GrileksCharmofMight = std.Items.create(MODNAME,'grilekscharmofmight',19951)
GrileksCharmofMight.Quality.setBlue()
export let GrileksCharmofValor = std.Items.create(MODNAME,'grilekscharmofnalor',19952)
GrileksCharmofValor.Quality.setBlue()
export let RenatakisCharmofBeasts = std.Items.create(MODNAME,'renatakischarmofbeasts',19953)
RenatakisCharmofBeasts.Quality.setBlue()
export let RenatakisCharmofTrickery = std.Items.create(MODNAME,'renatakischarmoftrickery',19954)
RenatakisCharmofTrickery.Quality.setBlue()
export let WushoolaysCharmofNature = std.Items.create(MODNAME,'wushoolayscharmofnature',19955)
WushoolaysCharmofNature.Quality.setBlue()
export let WushoolaysCharmofSpirits = std.Items.create(MODNAME,'wushoolayscharmofspirits',19956)
WushoolaysCharmofSpirits.Quality.setBlue()
export let HazzarahsCharmofDestruction = std.Items.create(MODNAME,'hazzarahscharmofdestruction',19957)
HazzarahsCharmofDestruction.Quality.setBlue()
export let HazzarahsCharmofHealing = std.Items.create(MODNAME,'hazzarahscharmofhealing',19958)
HazzarahsCharmofHealing.Quality.setBlue()
export let HazzarahsCharmofMagic = std.Items.create(MODNAME,'hazzarahscharmofmagic',19959)
HazzarahsCharmofMagic.Quality.setBlue()
export let PristineEnchantedSouthSeasKelp = std.Items.create(MODNAME,'pristineenchantedsouthseaskelp',19613)
PristineEnchantedSouthSeasKelp.Quality.setBlue()
export let JewelofKajaro = std.Items.create(MODNAME,'jewelofkajaro',19601)
JewelofKajaro.Quality.setBlue()
export let MaelstromsWrath = std.Items.create(MODNAME,'maelstromswrath',19621)
MaelstromsWrath.Quality.setBlue()
export let HerosBrand = std.Items.create(MODNAME,'herosBrand',19588)
HerosBrand.Quality.setBlue()
export let TheAllSeeingEyeofZuldazar = std.Items.create(MODNAME,'theallseeingeyeofzuldazar',19594)
TheAllSeeingEyeofZuldazar.Quality.setBlue()
export let UnmarredVisionofVoodress = std.Items.create(MODNAME,'unmarredvisionofvoodress',19609)
UnmarredVisionofVoodress.Quality.setBlue()
export let ZandalarianShadowMasteryTalisman = std.Items.create(MODNAME,'zandalarianshadowmasterytalisman',19617)
ZandalarianShadowMasteryTalisman.Quality.setBlue()
export let KezansUnstoppableTaint = std.Items.create(MODNAME,'kezansunstoppabletaint',19605)
KezansUnstoppableTaint.Quality.setBlue()
export let RageofMugamba = std.Items.create(MODNAME,'rageofmugamba',19577)
RageofMugamba.Quality.setBlue()


export let FourDazzlingLongsword = std.Items.create(MODNAME,'fourdazzlinglongsword',869)
FourDazzlingLongsword.Name.enGB.set('Sword of Light')
FourDazzlingLongsword.Quality.setPurple()
export let FourNightblade = std.Items.create(MODNAME,'fournightblade',1982)
FourNightblade.Name.enGB.set('Dreadtalon')
FourNightblade.Quality.setPurple()
export let FourFieryWarAxe = std.Items.create(MODNAME,'fourfierywaraxe',870)
FourFieryWarAxe.Name.enGB.set('Incindiary Axe')
FourFieryWarAxe.Quality.setPurple()
export let FourArdentCustodian = std.Items.create(MODNAME,'fourardentcustodian',868)
FourArdentCustodian.Name.enGB.set('Ardent Pummeler')
FourArdentCustodian.Quality.setPurple()
export let FourStaffofJordan = std.Items.create(MODNAME,'fourstaffofjordan',873)
FourStaffofJordan.Name.enGB.set('Staff of Incantations')
FourStaffofJordan.Quality.setPurple()
export let FourTheGreenTower = std.Items.create(MODNAME,'fourthegreentower',1204)
FourTheGreenTower.Name.enGB.set('Stalward Defender')
FourTheGreenTower.Quality.setPurple()
export let FourBowofSearingArrows = std.Items.create(MODNAME,'fourbowofsearingarrows',2825)
FourBowofSearingArrows.Name.enGB.set('Ragefire Longbow')
FourBowofSearingArrows.Quality.setPurple()
export let FourUnderworldBand = std.Items.create(MODNAME,'fourunderworldband',1980)
FourUnderworldBand.Name.enGB.set('Ring of Lost Hope')
FourUnderworldBand.Quality.setPurple()
export let FourGutRipper = std.Items.create(MODNAME,'fourgutripper',2164)
FourGutRipper.Name.enGB.set('Rend')
FourGutRipper.Quality.setPurple()
export let FourIronfoe = std.Items.create(MODNAME,'fourironfoe',11684)
FourIronfoe.Name.enGB.set('The Clobbermaster')
FourIronfoe.Quality.setPurple()
export let FourEskhandarsRightClaw = std.Items.create(MODNAME,'foureskhandarsrightclaw',18203)
FourEskhandarsRightClaw.Name.enGB.set('Dismembered Bear Claw')
FourEskhandarsRightClaw.Quality.setPurple()
export let FourEskhandarsLeftClaw = std.Items.create(MODNAME,'foureskhandarsleftclaw',18202)
FourEskhandarsLeftClaw.Name.enGB.set('Dismembered Bear Fist')
FourEskhandarsLeftClaw.Quality.setPurple()


export let GenesisHelm = std.Items.create(MODNAME,'genesishelm',21353)
GenesisHelm.Quality.setBlue()
export let GenesisShoulderpads = std.Items.create(MODNAME,'genesisshoulderpads',21354)
GenesisShoulderpads.Quality.setBlue()
export let GenesisBoots = std.Items.create(MODNAME,'genesisboots',21355)
GenesisBoots.Quality.setBlue()
export let GenesisTrousers = std.Items.create(MODNAME,'genesistrousers',21356)
GenesisTrousers.Quality.setBlue()
export let GenesisVest = std.Items.create(MODNAME,'genesisvest',21357)
GenesisVest.Quality.setBlue()
export let EnigmaRobes = std.Items.create(MODNAME,'enigmarobes',21343)
EnigmaRobes.Quality.setBlue()
export let EnigmaBoots = std.Items.create(MODNAME,'enigmaboots',21344)
EnigmaBoots.Quality.setBlue()
export let EnigmaShoulderpads = std.Items.create(MODNAME,'enigmashoulderpads',21345)
EnigmaShoulderpads.Quality.setBlue()
export let EnigmaLeggings = std.Items.create(MODNAME,'enigmaleggings',21346)
EnigmaLeggings.Quality.setBlue()
export let EnigmaCirclet = std.Items.create(MODNAME,'enigmacirclet',21347)
EnigmaCirclet.Quality.setBlue()
export let StrikersFootguards = std.Items.create(MODNAME,'strikersfootguards',21365)
StrikersFootguards.Quality.setBlue()
export let StrikersDiadem = std.Items.create(MODNAME,'strikersdiadem',21366)
StrikersDiadem.Quality.setBlue()
export let StrikersPauldrons = std.Items.create(MODNAME,'strikerspauldrons',21367)
StrikersPauldrons.Quality.setBlue()
export let StrikersLeggings = std.Items.create(MODNAME,'strikersleggings',21368)
StrikersLeggings.Quality.setBlue()
export let StrikersHauberk = std.Items.create(MODNAME,'strikershauberk',21370)
StrikersHauberk.Quality.setBlue()
export let AvengersCrown = std.Items.create(MODNAME,'avengerscrown',21387)
AvengersCrown.Quality.setBlue()
export let AvengersGreaves = std.Items.create(MODNAME,'avengersgreaves',21388)
AvengersGreaves.Quality.setBlue()
export let AvengersBreastplate = std.Items.create(MODNAME,'avengersbreastplate',21389)
AvengersBreastplate.Quality.setBlue()
export let AvengersLegguards = std.Items.create(MODNAME,'avengerslegguards',21390)
AvengersLegguards.Quality.setBlue()
export let AvengersPauldrons = std.Items.create(MODNAME,'avengerspauldrons',21391)
AvengersPauldrons.Quality.setBlue()
export let TiaraoftheOracle = std.Items.create(MODNAME,'tiaraoftheoracle',21348)
TiaraoftheOracle.Quality.setBlue()
export let FootwrapsoftheOracle = std.Items.create(MODNAME,'Footwrapsoftheoracle',21349)
FootwrapsoftheOracle.Quality.setBlue()
export let MantleoftheOracle = std.Items.create(MODNAME,'mantleoftheoracle',21350)
MantleoftheOracle.Quality.setBlue()
export let VestmentsoftheOracle = std.Items.create(MODNAME,'Vestmentsoftheoracle',21351)
VestmentsoftheOracle.Quality.setBlue()
export let TrousersoftheOracle = std.Items.create(MODNAME,'trousersoftheoracle',21352)
TrousersoftheOracle.Quality.setBlue()
export let StormcallersDiadem = std.Items.create(MODNAME,'stormcallersdiadem',21372)
StormcallersDiadem.Quality.setBlue()
export let StormcallersFootguards = std.Items.create(MODNAME,'stormcallersfootguards',21373)
StormcallersFootguards.Quality.setBlue()
export let StormcallersHauberk = std.Items.create(MODNAME,'stormcallershauberk',21374)
StormcallersHauberk.Quality.setBlue()
export let StormcallersLeggings = std.Items.create(MODNAME,'stormcallersleggings',21375)
StormcallersLeggings.Quality.setBlue()
export let StormcallersPauldrons = std.Items.create(MODNAME,'stormcallerspauldrons',21376)
StormcallersPauldrons.Quality.setBlue()
export let DeathdealersBoots = std.Items.create(MODNAME,'deathdealersboots',21359)
DeathdealersBoots.Quality.setBlue()
export let DeathdealersHelm = std.Items.create(MODNAME,'deathdealershelm',21360)
DeathdealersHelm.Quality.setBlue()
export let DeathdealersSpaulders = std.Items.create(MODNAME,'deathdealersspaulders',21361)
DeathdealersSpaulders.Quality.setBlue()
export let DeathdealersLeggings = std.Items.create(MODNAME,'deathdealersleggings',21362)
DeathdealersLeggings.Quality.setBlue()
export let DeathdealersVest = std.Items.create(MODNAME,'deathdealersvest',21364)
DeathdealersVest.Quality.setBlue()
export let DoomcallersRobes = std.Items.create(MODNAME,'doomcallersrobes',21334)
DoomcallersRobes.Quality.setBlue()
export let DoomcallersMantle = std.Items.create(MODNAME,'doomcallersmantle',21335)
DoomcallersMantle.Quality.setBlue()
export let DoomcallersTrousers = std.Items.create(MODNAME,'doomcallerstrousers',21336)
DoomcallersTrousers.Quality.setBlue()
export let DoomcallersCirclet = std.Items.create(MODNAME,'doomcallerscirclet',21337)
DoomcallersCirclet.Quality.setBlue()
export let DoomcallersFootwraps = std.Items.create(MODNAME,'doomcallersfootwraps',21338)
DoomcallersFootwraps.Quality.setBlue()
export let ConquerorsCrown = std.Items.create(MODNAME,'conquerorscrown',21329)
ConquerorsCrown.Quality.setBlue()
export let ConquerorsSpaulders = std.Items.create(MODNAME,'conquerorsspaulders',21330)
ConquerorsSpaulders.Quality.setBlue()
export let ConquerorsBreastplate = std.Items.create(MODNAME,'conquerorsbreastplate',21331)
ConquerorsBreastplate.Quality.setBlue()
export let ConquerorsLegguards = std.Items.create(MODNAME,'conquerorslegguards',21332)
ConquerorsLegguards.Quality.setBlue()
export let ConquerorsGreaves = std.Items.create(MODNAME,'conquerorsgreaves',21333)
ConquerorsGreaves.Quality.setBlue()
