import { std } from "tswow-stdlib"
import { MODNAME } from "../../modname"

import { SpiritIV, ProtectionIV, AgilityIV, IntellectIV, StrengthIV, StaminaIV } from "./zone-4-item-spells"

export let MassiveRedPouch = std.Items.create(MODNAME,'massiveredpouch',805)
MassiveRedPouch.Quality.setBlue()
MassiveRedPouch.ContainerSlots.set(22)
export let MassiveBluePouch = std.Items.create(MODNAME,'massivebluepouch',828)
MassiveBluePouch.Quality.setBlue()
MassiveBluePouch.ContainerSlots.set(22)
export let MassiveBlackPouch = std.Items.create(MODNAME,'massiveblackpouch',5571)
MassiveBlackPouch.Quality.setBlue()
MassiveBlackPouch.ContainerSlots.set(22)
export let MassiveGreenPouch = std.Items.create(MODNAME,'massivegreenpouch',5572)
MassiveGreenPouch.Quality.setBlue()
MassiveGreenPouch.ContainerSlots.set(22)

export let ZandalarVindicatorBreastplate = std.Items.create(MODNAME,'zandalarvindicatorbreastplate',19822)
ZandalarVindicatorBreastplate.Quality.setBlue()
ZandalarVindicatorBreastplate.MaxCount.set(0)
export let ZandalarVindicatorBelt = std.Items.create(MODNAME,'zandalarvindicatorbelt',19823)
ZandalarVindicatorBelt.Quality.setBlue()
ZandalarVindicatorBelt.MaxCount.set(0)
export let ZandalarVindicatorArmguards = std.Items.create(MODNAME,'zandalarvindicatorarmguards',19824)
ZandalarVindicatorArmguards.Quality.setBlue()
ZandalarVindicatorArmguards.MaxCount.set(0)
export let ZandalarFreethinkerBreastplate = std.Items.create(MODNAME,'zandalarfreethinkerbreastplate',19825)
ZandalarFreethinkerBreastplate.Quality.setBlue()
ZandalarFreethinkerBreastplate.MaxCount.set(0)
export let ZandalarFreethinkerBelt = std.Items.create(MODNAME,'zandalarfreethinkerbelt',19826)
ZandalarFreethinkerBelt.Quality.setBlue()
ZandalarFreethinkerBelt.MaxCount.set(0)
export let ZandalarFreethinkerArmguards = std.Items.create(MODNAME,'zandalarfreethinkerarmguards',19827)
ZandalarFreethinkerArmguards.Quality.setBlue()
ZandalarFreethinkerArmguards.MaxCount.set(0)
export let ZandalarAugurHauberk = std.Items.create(MODNAME,'zandalaraugurHauberk',19828)
ZandalarAugurHauberk.Quality.setBlue()
ZandalarAugurHauberk.MaxCount.set(0)
export let ZandalarAugurBelt = std.Items.create(MODNAME,'zandalaraugurbelt',19829)
ZandalarAugurBelt.Quality.setBlue()
ZandalarAugurBelt.MaxCount.set(0)
export let ZandalarAugurBracers = std.Items.create(MODNAME,'zandalaraugurbracers',19830)
ZandalarAugurBracers.Quality.setBlue()
ZandalarAugurBracers.MaxCount.set(0)
export let ZandalarPredatorMantle = std.Items.create(MODNAME,'zandalarpredatormantle',19831)
ZandalarPredatorMantle.Quality.setBlue()
ZandalarPredatorMantle.MaxCount.set(0)
export let ZandalarPredatorBelt = std.Items.create(MODNAME,'zandalarpredatorbelt',19832)
ZandalarPredatorBelt.Quality.setBlue()
ZandalarPredatorBelt.MaxCount.set(0)
export let ZandalarPredatorBracers = std.Items.create(MODNAME,'zandalarpredatorbracers',19833)
ZandalarPredatorBracers.Quality.setBlue()
ZandalarPredatorBracers.MaxCount.set(0)
export let ZandalarMadcapTunic = std.Items.create(MODNAME,'zandalarmadcaptunic',19834)
ZandalarMadcapTunic.Quality.setBlue()
ZandalarMadcapTunic.MaxCount.set(0)
export let ZandalarMadcapMantle = std.Items.create(MODNAME,'zandalarmadcapmantle',19835)
ZandalarMadcapMantle.Quality.setBlue()
ZandalarMadcapMantle.MaxCount.set(0)
export let ZandalarMadcapBracers = std.Items.create(MODNAME,'zandalarmadcapbracers',19836)
ZandalarMadcapBracers.Quality.setBlue()
ZandalarMadcapBracers.MaxCount.set(0)
export let ZandalarHaruspexTunic = std.Items.create(MODNAME,'zandalarharuspextunic',19838)
ZandalarHaruspexTunic.Quality.setBlue()
ZandalarHaruspexTunic.MaxCount.set(0)
export let ZandalarHaruspexBelt = std.Items.create(MODNAME,'zandalarharuspexbelt',19839)
ZandalarHaruspexBelt.Quality.setBlue()
ZandalarHaruspexBelt.MaxCount.set(0)
export let ZandalarHaruspexBracers = std.Items.create(MODNAME,'zandalarharuspexbracers',19840)
ZandalarHaruspexBracers.Quality.setBlue()
ZandalarHaruspexBracers.MaxCount.set(0)
export let ZandalarConfessorMantle = std.Items.create(MODNAME,'zandalarconfessormantle',19841)
ZandalarConfessorMantle.Quality.setBlue()
ZandalarConfessorMantle.MaxCount.set(0)
export let ZandalarConfessorBindings = std.Items.create(MODNAME,'zandalarconfessorbindings',19842)
ZandalarConfessorBindings.Quality.setBlue()
ZandalarConfessorBindings.MaxCount.set(0)
export let ZandalarConfessorWraps = std.Items.create(MODNAME,'zandalarconfessorwraps',19843)
ZandalarConfessorWraps.Quality.setBlue()
ZandalarConfessorWraps.MaxCount.set(0)
export let ZandalarIllusionistMantle = std.Items.create(MODNAME,'zandalarillusionistmantle',19845)
ZandalarIllusionistMantle.Quality.setBlue()
ZandalarIllusionistMantle.MaxCount.set(0)
export let ZandalarIllusionistWraps = std.Items.create(MODNAME,'zandalarillusionistwraps',19846)
ZandalarIllusionistWraps.Quality.setBlue()
ZandalarIllusionistWraps.MaxCount.set(0)
export let ZandalarDemoniacWraps = std.Items.create(MODNAME,'zandalardemoniacwraps',19848)
ZandalarDemoniacWraps.Quality.setBlue()
ZandalarDemoniacWraps.MaxCount.set(0)
export let ZandalarDemoniacMantle = std.Items.create(MODNAME,'zandalardemoniacmantle',19849)
ZandalarDemoniacMantle.Quality.setBlue()
ZandalarDemoniacMantle.MaxCount.set(0)
export let ZandalarHonorToken = std.Items.create(MODNAME,'zandalarhonortoken',19858)
ZandalarHonorToken.Quality.setBlue()
ZandalarHonorToken.MaxCount.set(0)
export let ZandalarianHeroBadge = std.Items.create(MODNAME,'zandalarianherobadge',19948)
ZandalarianHeroBadge.Quality.setBlue()
ZandalarianHeroBadge.MaxCount.set(0)
export let ZandalarianHeroMedallion = std.Items.create(MODNAME,'zandalarianheromedallion',19949)
ZandalarianHeroMedallion.Quality.setBlue()
ZandalarianHeroMedallion.MaxCount.set(0)
export let ZandalarianHeroCharm = std.Items.create(MODNAME,'zandalarianherocharm',19950)
ZandalarianHeroCharm.Quality.setBlue()
ZandalarianHeroCharm.MaxCount.set(0)
export let ZandalarDemoniacRobe = std.Items.create(MODNAME,'zandalardemoniacrobe',20033)
ZandalarDemoniacRobe.Quality.setBlue()
ZandalarDemoniacRobe.MaxCount.set(0)
export let ZandalarIllusionistRobe = std.Items.create(MODNAME,'zandalarillusionistrobe',20034)
ZandalarIllusionistRobe.Quality.setBlue()
ZandalarIllusionistRobe.MaxCount.set(0)
export let ZandalarSignetofMojo = std.Items.create(MODNAME,'zandalarsignetofmojo',20076)
ZandalarSignetofMojo.Quality.setBlue()
ZandalarSignetofMojo.MaxCount.set(0)
export let ZandalarSignetofMight = std.Items.create(MODNAME,'zandalarsignetofmight',20077)
ZandalarSignetofMight.Quality.setBlue()
ZandalarSignetofMight.MaxCount.set(0)
export let ZandalarSignetofSerenity = std.Items.create(MODNAME,'zandalarsignetofserenity',20078)
ZandalarSignetofSerenity.Quality.setBlue()
ZandalarSignetofSerenity.MaxCount.set(0)
export let GrileksCharmofMight = std.Items.create(MODNAME,'grilekscharmofmight',19951)
GrileksCharmofMight.Quality.setBlue()
GrileksCharmofMight.MaxCount.set(0)
export let GrileksCharmofValor = std.Items.create(MODNAME,'grilekscharmofnalor',19952)
GrileksCharmofValor.Quality.setBlue()
GrileksCharmofValor.MaxCount.set(0)
export let RenatakisCharmofBeasts = std.Items.create(MODNAME,'renatakischarmofbeasts',19953)
RenatakisCharmofBeasts.Quality.setBlue()
RenatakisCharmofBeasts.MaxCount.set(0)
export let RenatakisCharmofTrickery = std.Items.create(MODNAME,'renatakischarmoftrickery',19954)
RenatakisCharmofTrickery.Quality.setBlue()
RenatakisCharmofTrickery.MaxCount.set(0)
export let WushoolaysCharmofNature = std.Items.create(MODNAME,'wushoolayscharmofnature',19955)
WushoolaysCharmofNature.Quality.setBlue()
WushoolaysCharmofNature.MaxCount.set(0)
export let WushoolaysCharmofSpirits = std.Items.create(MODNAME,'wushoolayscharmofspirits',19956)
WushoolaysCharmofSpirits.Quality.setBlue()
WushoolaysCharmofSpirits.MaxCount.set(0)
export let HazzarahsCharmofDestruction = std.Items.create(MODNAME,'hazzarahscharmofdestruction',19957)
HazzarahsCharmofDestruction.Quality.setBlue()
HazzarahsCharmofDestruction.MaxCount.set(0)
export let HazzarahsCharmofHealing = std.Items.create(MODNAME,'hazzarahscharmofhealing',19958)
HazzarahsCharmofHealing.Quality.setBlue()
HazzarahsCharmofHealing.MaxCount.set(0)
export let HazzarahsCharmofMagic = std.Items.create(MODNAME,'hazzarahscharmofmagic',19959)
HazzarahsCharmofMagic.Quality.setBlue()
HazzarahsCharmofMagic.MaxCount.set(0)
export let PristineEnchantedSouthSeasKelp = std.Items.create(MODNAME,'pristineenchantedsouthseaskelp',19613)
PristineEnchantedSouthSeasKelp.Quality.setBlue()
PristineEnchantedSouthSeasKelp.MaxCount.set(0)
export let JewelofKajaro = std.Items.create(MODNAME,'jewelofkajaro',19601)
JewelofKajaro.Quality.setBlue()
JewelofKajaro.MaxCount.set(0)
export let MaelstromsWrath = std.Items.create(MODNAME,'maelstromswrath',19621)
MaelstromsWrath.Quality.setBlue()
MaelstromsWrath.MaxCount.set(0)
export let HerosBrand = std.Items.create(MODNAME,'herosBrand',19588)
HerosBrand.Quality.setBlue()
HerosBrand.MaxCount.set(0)
export let TheAllSeeingEyeofZuldazar = std.Items.create(MODNAME,'theallseeingeyeofzuldazar',19594)
TheAllSeeingEyeofZuldazar.Quality.setBlue()
TheAllSeeingEyeofZuldazar.MaxCount.set(0)
export let UnmarredVisionofVoodress = std.Items.create(MODNAME,'unmarredvisionofvoodress',19609)
UnmarredVisionofVoodress.Quality.setBlue()
UnmarredVisionofVoodress.MaxCount.set(0)
export let ZandalarianShadowMasteryTalisman = std.Items.create(MODNAME,'zandalarianshadowmasterytalisman',19617)
ZandalarianShadowMasteryTalisman.Quality.setBlue()
ZandalarianShadowMasteryTalisman.MaxCount.set(0)
export let KezansUnstoppableTaint = std.Items.create(MODNAME,'kezansunstoppabletaint',19605)
KezansUnstoppableTaint.Quality.setBlue()
KezansUnstoppableTaint.MaxCount.set(0)
export let RageofMugamba = std.Items.create(MODNAME,'rageofmugamba',19577)
RageofMugamba.Quality.setBlue()
RageofMugamba.MaxCount.set(0)


export let FourDazzlingLongsword = std.Items.create(MODNAME,'fourdazzlinglongsword',869)
FourDazzlingLongsword.Name.enGB.set('Sword of Light')
FourDazzlingLongsword.Quality.setPurple()
export let FourNightblade = std.Items.create(MODNAME,'fournightblade',1982)
FourNightblade.Name.enGB.set('Dreadtalon')
FourNightblade.Quality.setPurple()
export let FourFieryWarAxe = std.Items.create(MODNAME,'fourfierywaraxe',870)
FourFieryWarAxe.Name.enGB.set('Incindiary Axe')
FourFieryWarAxe.Quality.setPurple()
export let FourArdentCustodian = std.Items.create(MODNAME,'fourardentcustodian',868)
FourArdentCustodian.Name.enGB.set('Ardent Pummeler')
FourArdentCustodian.Quality.setPurple()
export let FourStaffofJordan = std.Items.create(MODNAME,'fourstaffofjordan',873)
FourStaffofJordan.Name.enGB.set('Staff of Incantations')
FourStaffofJordan.Quality.setPurple()
export let FourTheGreenTower = std.Items.create(MODNAME,'fourthegreentower',1204)
FourTheGreenTower.Name.enGB.set('Stalward Defender')
FourTheGreenTower.Quality.setPurple()
export let FourBowofSearingArrows = std.Items.create(MODNAME,'fourbowofsearingarrows',2825)
FourBowofSearingArrows.Name.enGB.set('Ragefire Longbow')
FourBowofSearingArrows.Quality.setPurple()
export let FourUnderworldBand = std.Items.create(MODNAME,'fourunderworldband',1980)
FourUnderworldBand.Name.enGB.set('Ring of Lost Hope')
FourUnderworldBand.Quality.setPurple()
export let FourGutRipper = std.Items.create(MODNAME,'fourgutripper',2164)
FourGutRipper.Name.enGB.set('Rend')
FourGutRipper.Quality.setPurple()
export let FourIronfoe = std.Items.create(MODNAME,'fourironfoe',11684)
FourIronfoe.Name.enGB.set('The Clobbermaster')
FourIronfoe.Quality.setPurple()
export let FourEskhandarsRightClaw = std.Items.create(MODNAME,'foureskhandarsrightclaw',18203)
FourEskhandarsRightClaw.Name.enGB.set('Dismembered Bear Claw')
FourEskhandarsRightClaw.Quality.setPurple()
export let FourEskhandarsLeftClaw = std.Items.create(MODNAME,'foureskhandarsleftclaw',18202)
FourEskhandarsLeftClaw.Name.enGB.set('Dismembered Bear Fist')
FourEskhandarsLeftClaw.Quality.setPurple()


export let GenesisHelm = std.Items.create(MODNAME,'genesishelm',21353)
GenesisHelm.Quality.setBlue()
GenesisHelm.MaxCount.set(0)
export let GenesisShoulderpads = std.Items.create(MODNAME,'genesisshoulderpads',21354)
GenesisShoulderpads.Quality.setBlue()
GenesisShoulderpads.MaxCount.set(0)
export let GenesisBoots = std.Items.create(MODNAME,'genesisboots',21355)
GenesisBoots.Quality.setBlue()
GenesisBoots.MaxCount.set(0)
export let GenesisTrousers = std.Items.create(MODNAME,'genesistrousers',21356)
GenesisTrousers.Quality.setBlue()
GenesisTrousers.MaxCount.set(0)
export let GenesisVest = std.Items.create(MODNAME,'genesisvest',21357)
GenesisVest.Quality.setBlue()
GenesisVest.MaxCount.set(0)
export let EnigmaRobes = std.Items.create(MODNAME,'enigmarobes',21343)
EnigmaRobes.Quality.setBlue()
EnigmaRobes.MaxCount.set(0)
export let EnigmaBoots = std.Items.create(MODNAME,'enigmaboots',21344)
EnigmaBoots.Quality.setBlue()
EnigmaBoots.MaxCount.set(0)
export let EnigmaShoulderpads = std.Items.create(MODNAME,'enigmashoulderpads',21345)
EnigmaShoulderpads.Quality.setBlue()
EnigmaShoulderpads.MaxCount.set(0)
export let EnigmaLeggings = std.Items.create(MODNAME,'enigmaleggings',21346)
EnigmaLeggings.Quality.setBlue()
EnigmaLeggings.MaxCount.set(0)
export let EnigmaCirclet = std.Items.create(MODNAME,'enigmacirclet',21347)
EnigmaCirclet.Quality.setBlue()
EnigmaCirclet.MaxCount.set(0)
export let StrikersFootguards = std.Items.create(MODNAME,'strikersfootguards',21365)
StrikersFootguards.Quality.setBlue()
StrikersFootguards.MaxCount.set(0)
export let StrikersDiadem = std.Items.create(MODNAME,'strikersdiadem',21366)
StrikersDiadem.Quality.setBlue()
StrikersDiadem.MaxCount.set(0)
export let StrikersPauldrons = std.Items.create(MODNAME,'strikerspauldrons',21367)
StrikersPauldrons.Quality.setBlue()
StrikersPauldrons.MaxCount.set(0)
export let StrikersLeggings = std.Items.create(MODNAME,'strikersleggings',21368)
StrikersLeggings.Quality.setBlue()
StrikersLeggings.MaxCount.set(0)
export let StrikersHauberk = std.Items.create(MODNAME,'strikershauberk',21370)
StrikersHauberk.Quality.setBlue()
StrikersHauberk.MaxCount.set(0)
export let AvengersCrown = std.Items.create(MODNAME,'avengerscrown',21387)
AvengersCrown.Quality.setBlue()
AvengersCrown.MaxCount.set(0)
export let AvengersGreaves = std.Items.create(MODNAME,'avengersgreaves',21388)
AvengersGreaves.Quality.setBlue()
AvengersGreaves.MaxCount.set(0)
export let AvengersBreastplate = std.Items.create(MODNAME,'avengersbreastplate',21389)
AvengersBreastplate.Quality.setBlue()
AvengersBreastplate.MaxCount.set(0)
export let AvengersLegguards = std.Items.create(MODNAME,'avengerslegguards',21390)
AvengersLegguards.Quality.setBlue()
AvengersLegguards.MaxCount.set(0)
export let AvengersPauldrons = std.Items.create(MODNAME,'avengerspauldrons',21391)
AvengersPauldrons.Quality.setBlue()
AvengersPauldrons.MaxCount.set(0)
export let TiaraoftheOracle = std.Items.create(MODNAME,'tiaraoftheoracle',21348)
TiaraoftheOracle.Quality.setBlue()
TiaraoftheOracle.MaxCount.set(0)
export let FootwrapsoftheOracle = std.Items.create(MODNAME,'Footwrapsoftheoracle',21349)
FootwrapsoftheOracle.Quality.setBlue()
FootwrapsoftheOracle.MaxCount.set(0)
export let MantleoftheOracle = std.Items.create(MODNAME,'mantleoftheoracle',21350)
MantleoftheOracle.Quality.setBlue()
MantleoftheOracle.MaxCount.set(0)
export let VestmentsoftheOracle = std.Items.create(MODNAME,'Vestmentsoftheoracle',21351)
VestmentsoftheOracle.Quality.setBlue()
VestmentsoftheOracle.MaxCount.set(0)
export let TrousersoftheOracle = std.Items.create(MODNAME,'trousersoftheoracle',21352)
TrousersoftheOracle.Quality.setBlue()
TrousersoftheOracle.MaxCount.set(0)
export let StormcallersDiadem = std.Items.create(MODNAME,'stormcallersdiadem',21372)
StormcallersDiadem.Quality.setBlue()
StormcallersDiadem.MaxCount.set(0)
export let StormcallersFootguards = std.Items.create(MODNAME,'stormcallersfootguards',21373)
StormcallersFootguards.Quality.setBlue()
StormcallersFootguards.MaxCount.set(0)
export let StormcallersHauberk = std.Items.create(MODNAME,'stormcallershauberk',21374)
StormcallersHauberk.Quality.setBlue()
StormcallersHauberk.MaxCount.set(0)
export let StormcallersLeggings = std.Items.create(MODNAME,'stormcallersleggings',21375)
StormcallersLeggings.Quality.setBlue()
StormcallersLeggings.MaxCount.set(0)
export let StormcallersPauldrons = std.Items.create(MODNAME,'stormcallerspauldrons',21376)
StormcallersPauldrons.Quality.setBlue()
StormcallersPauldrons.MaxCount.set(0)
export let DeathdealersBoots = std.Items.create(MODNAME,'deathdealersboots',21359)
DeathdealersBoots.Quality.setBlue()
DeathdealersBoots.MaxCount.set(0)
export let DeathdealersHelm = std.Items.create(MODNAME,'deathdealershelm',21360)
DeathdealersHelm.Quality.setBlue()
DeathdealersHelm.MaxCount.set(0)
export let DeathdealersSpaulders = std.Items.create(MODNAME,'deathdealersspaulders',21361)
DeathdealersSpaulders.Quality.setBlue()
DeathdealersSpaulders.MaxCount.set(0)
export let DeathdealersLeggings = std.Items.create(MODNAME,'deathdealersleggings',21362)
DeathdealersLeggings.Quality.setBlue()
DeathdealersLeggings.MaxCount.set(0)
export let DeathdealersVest = std.Items.create(MODNAME,'deathdealersvest',21364)
DeathdealersVest.Quality.setBlue()
DeathdealersVest.MaxCount.set(0)
export let DoomcallersRobes = std.Items.create(MODNAME,'doomcallersrobes',21334)
DoomcallersRobes.Quality.setBlue()
DoomcallersRobes.MaxCount.set(0)
export let DoomcallersMantle = std.Items.create(MODNAME,'doomcallersmantle',21335)
DoomcallersMantle.Quality.setBlue()
DoomcallersMantle.MaxCount.set(0)
export let DoomcallersTrousers = std.Items.create(MODNAME,'doomcallerstrousers',21336)
DoomcallersTrousers.Quality.setBlue()
DoomcallersTrousers.MaxCount.set(0)
export let DoomcallersCirclet = std.Items.create(MODNAME,'doomcallerscirclet',21337)
DoomcallersCirclet.Quality.setBlue()
DoomcallersCirclet.MaxCount.set(0)
export let DoomcallersFootwraps = std.Items.create(MODNAME,'doomcallersfootwraps',21338)
DoomcallersFootwraps.Quality.setBlue()
DoomcallersFootwraps.MaxCount.set(0)
export let ConquerorsCrown = std.Items.create(MODNAME,'conquerorscrown',21329)
ConquerorsCrown.Quality.setBlue()
ConquerorsCrown.MaxCount.set(0)
export let ConquerorsSpaulders = std.Items.create(MODNAME,'conquerorsspaulders',21330)
ConquerorsSpaulders.Quality.setBlue()
ConquerorsSpaulders.MaxCount.set(0)
export let ConquerorsBreastplate = std.Items.create(MODNAME,'conquerorsbreastplate',21331)
ConquerorsBreastplate.Quality.setBlue()
ConquerorsBreastplate.MaxCount.set(0)
export let ConquerorsLegguards = std.Items.create(MODNAME,'conquerorslegguards',21332)
ConquerorsLegguards.Quality.setBlue()
ConquerorsLegguards.MaxCount.set(0)
export let ConquerorsGreaves = std.Items.create(MODNAME,'conquerorsgreaves',21333)
ConquerorsGreaves.Quality.setBlue()
ConquerorsGreaves.MaxCount.set(0)

//ARENA OF CHAMPIONS ITEMS
export let EyeofGruul = std.Items.create(MODNAME,'eyeofgruul',28823)
EyeofGruul.Name.enGB.set('Badge of Honor')
EyeofGruul.Quality.setPurple()
EyeofGruul.MaxCount.set(0)
export let DragonspineTrophy = std.Items.create(MODNAME,'dragonspinetrophy',28830)
DragonspineTrophy.Quality.setPurple()
DragonspineTrophy.Name.enGB.set('Badge of Zeal')
DragonspineTrophy.MaxCount.set(0)
export let MoroesLuckyPocketWatch = std.Items.create(MODNAME,'moroesluckypocketwatch',28528)
MoroesLuckyPocketWatch.Quality.setPurple()
MoroesLuckyPocketWatch.Name.enGB.set('Edge of Time')
MoroesLuckyPocketWatch.MaxCount.set(0)
export let RomulosPoisonVial = std.Items.create(MODNAME,'romulospoisonvial',28579)
RomulosPoisonVial.Quality.setPurple()
RomulosPoisonVial.Name.enGB.set('Vial of Living Poison')
RomulosPoisonVial.MaxCount.set(0)
export let LightningCapacitor = std.Items.create(MODNAME,'lightningcapacitor',28785)
LightningCapacitor.Quality.setPurple()
LightningCapacitor.Name.enGB.set('Bottled Lightning')
LightningCapacitor.MaxCount.set(0)
export let VioletEye = std.Items.create(MODNAME,'voioleteye',28727)
VioletEye.Quality.setPurple()
VioletEye.Name.enGB.set('Warders Pendant')
VioletEye.MaxCount.set(0)
export let Sulfuras = std.Items.create(MODNAME,'sulfuras',17182)
Sulfuras.Quality.setOrange()
Sulfuras.Name.enGB.set('Flametaur Mallet')
export let Thunderfury = std.Items.create(MODNAME,'thunderfury',19019)
Thunderfury.Quality.setOrange()
Thunderfury.Name.enGB.set('Blade of Flowing Currents')
export let WarglaiveMH = std.Items.create(MODNAME,'warglaivemh',32837)
WarglaiveMH.Quality.setOrange()
WarglaiveMH.Name.enGB.set('Felglaive')
export let WarglaiveOH = std.Items.create(MODNAME,'warglaiveoh',32838)
WarglaiveOH.Quality.setOrange()
WarglaiveOH.Name.enGB.set('Felglaive')
export let Thoridal = std.Items.create(MODNAME,'thoridal',34334)
Thoridal.Quality.setOrange()
Thoridal.Name.enGB.set('Fatespinner Longbow')


export let FourthScrollofSpiritVIII = std.Items.create(MODNAME,'fourthscrollofspiritviii',43465)
FourthScrollofSpiritVIII.Name.enGB.set('Scroll of Spirit')
FourthScrollofSpiritVIII.Quality.setWhite()
FourthScrollofSpiritVIII.Spells.clear(0)
FourthScrollofSpiritVIII.Spells.add(SpiritIV.ID,undefined,undefined,-1)
FourthScrollofSpiritVIII.RequiredLevel.set(0)
export let FourthScrollofProtectionVIII = std.Items.create(MODNAME,'fourthscrollofprotectionviii',43465)
FourthScrollofProtectionVIII.Name.enGB.set('Scroll of Protection')
FourthScrollofProtectionVIII.Quality.setWhite()
FourthScrollofProtectionVIII.Spells.clear(0)
FourthScrollofProtectionVIII.Spells.add(ProtectionIV.ID,undefined,undefined,-1)
FourthScrollofProtectionVIII.RequiredLevel.set(0)
export let FourthScrollofAgilityVIII = std.Items.create(MODNAME,'fourthscrollofagilityviii',43465)
FourthScrollofAgilityVIII.Name.enGB.set('Scroll of Agility')
FourthScrollofAgilityVIII.Quality.setWhite()
FourthScrollofAgilityVIII.Spells.clear(0)
FourthScrollofAgilityVIII.Spells.add(AgilityIV.ID,undefined,undefined,-1)
FourthScrollofAgilityVIII.RequiredLevel.set(0)
export let FourthScrollofIntellectVIII = std.Items.create(MODNAME,'fourthscrollofintellectviii',43465)
FourthScrollofIntellectVIII.Name.enGB.set('Scroll of Intellect')
FourthScrollofIntellectVIII.Quality.setWhite()
FourthScrollofIntellectVIII.Spells.clear(0)
FourthScrollofIntellectVIII.Spells.add(IntellectIV.ID,undefined,undefined,-1)
FourthScrollofIntellectVIII.RequiredLevel.set(0)
export let FourthScrollofStaminaVIII = std.Items.create(MODNAME,'fourthscrollofstaminaviii',43465)
FourthScrollofStaminaVIII.Name.enGB.set('Scroll of Stamina')
FourthScrollofStaminaVIII.Quality.setWhite()
FourthScrollofStaminaVIII.Spells.clear(0)
FourthScrollofStaminaVIII.Spells.add(StaminaIV.ID,undefined,undefined,-1)
FourthScrollofStaminaVIII.RequiredLevel.set(0)
export let FourthScrollofStrengthVIII = std.Items.create(MODNAME,'fourthscrollofstrengthviii',43465)
FourthScrollofStrengthVIII.Name.enGB.set('Scroll of Strength')
FourthScrollofStrengthVIII.Quality.setWhite()
FourthScrollofStrengthVIII.Spells.clear(0)
FourthScrollofStrengthVIII.Spells.add(StrengthIV.ID,undefined,undefined,-1)
FourthScrollofStrengthVIII.RequiredLevel.set(0)