import { MODNAME } from "../../modname"
import { std } from "tswow-stdlib"

/*Rare Items, 1 time purchase at vendor every several hours (TEST)*/
export let BlueMiningAxe = std.Items.create(MODNAME,'blueminingaxe',9378)
BlueMiningAxe.Quality.setBlue()
BlueMiningAxe.RequiredLevel.set(4)
BlueMiningAxe.Name.enGB.set('Stronson\'s Lucky Pickaxe')
BlueMiningAxe.Damage.clearAll()
BlueMiningAxe.Damage.addPhysical(10,14)
export let BlueShortSword = std.Items.create(MODNAME,'blueshortsword',9401)
BlueShortSword.Quality.setBlue()
BlueShortSword.RequiredLevel.set(4)
BlueShortSword.Name.enGB.set('Sturdy Blade')
BlueShortSword.Damage.clearAll()
BlueShortSword.Damage.addPhysical(7,18)
export let SlowFallShield = std.Items.create(MODNAME,'slowfallshield',9404)
SlowFallShield.Quality.setBlue()
SlowFallShield.RequiredLevel.set(4)
SlowFallShield.Name.enGB.set('Safety Buckler')
SlowFallShield.Armor.set(176)
export let VikingHelmet = std.Items.create(MODNAME,'vikinghelmet',9394)
VikingHelmet.Quality.setBlue()
VikingHelmet.RequiredLevel.set(4)
VikingHelmet.Name.enGB.set('Ramskull Helmet')
export let Hammerofflames = std.Items.create(MODNAME,'hammerofflames',9419)
Hammerofflames.Quality.setBlue()
Hammerofflames.RequiredLevel.set(4)
Hammerofflames.Name.enGB.set('Scorching Hammer')
Hammerofflames.Damage.clearAll()
Hammerofflames.Damage.addPhysical(3,7)
export let SpearofFate = std.Items.create(MODNAME,'spearoffate',9416)
SpearofFate.Quality.setBlue()
SpearofFate.RequiredLevel.set(4)
SpearofFate.Name.enGB.set('Spear of Fate')
SpearofFate.Damage.clearAll()
SpearofFate.Damage.addPhysical(13,17)
export let StolenRoyalGown = std.Items.create(MODNAME,'stolengown',6682)
StolenRoyalGown.Quality.setBlue()
StolenRoyalGown.RequiredLevel.set(4)
StolenRoyalGown.Name.enGB.set('Stolen Royal Gown')
export let DeathClutch = std.Items.create(MODNAME,'deathclutch',14503)
DeathClutch.Quality.setBlue()
DeathClutch.RequiredLevel.set(7)
DeathClutch.Name.enGB.set('Tempered Pauldrons')
export let KnowledgeTome = std.Items.create(MODNAME,'knowledgetome',13385)
KnowledgeTome.Quality.setBlue()
KnowledgeTome.RequiredLevel.set(6)
KnowledgeTome.Name.enGB.set('Mages\' Book')
export let MantleoftheSoulEater = std.Items.create(MODNAME,'souleatermantle',13374)
MantleoftheSoulEater.Quality.setBlue()
MantleoftheSoulEater.RequiredLevel.set(11)
MantleoftheSoulEater.Name.enGB.set('Mantle of the Soul Eater')
export let FocusStick = std.Items.create(MODNAME,'scepteroffocus',22329)
FocusStick.Quality.setBlue()
FocusStick.RequiredLevel.set(2)
FocusStick.Name.enGB.set('The Death Stick')


let ven = std.CreatureTemplates.load(78)
ven.Vendor.addItem(BlueMiningAxe.ID,1,3600,0)
ven.Vendor.addItem(BlueShortSword.ID,1,3600,0)
ven.Vendor.addItem(SlowFallShield.ID,1,3600,0)
ven.Vendor.addItem(VikingHelmet.ID,1,3600,0)
ven.Vendor.addItem(Hammerofflames.ID,1,3600,0)
ven.Vendor.addItem(SpearofFate.ID,1,3600,0)
ven.Vendor.addItem(StolenRoyalGown.ID,1,3600,0)
ven.Vendor.addItem(DeathClutch.ID,1,3600,0)
ven.Vendor.addItem(KnowledgeTome.ID,1,3600,0)
ven.Vendor.addItem(MantleoftheSoulEater.ID,1,3600,0)
ven.Vendor.addItem(FocusStick.ID,1,3600,0)

//Shaman Starting Items
export let WornMace = std.Items.load(36)
WornMace.DisplayInfo.Models.clearAll()
WornMace.DisplayInfo.copyFrom(36685)
WornMace.Quality.setWhite()
WornMace.Stats.addSpellPower(4)
WornMace.Stats.addCritRating(4)
WornMace.Stats.addIntellect(3)
export let WornWoodenShield = std.Items.load(2362)
WornWoodenShield.DisplayInfo.Models.clearAll()
WornWoodenShield.DisplayInfo.copyFrom(28153)
WornWoodenShield.Quality.setWhite()
WornWoodenShield.Stats.addSpellPower(3)
WornWoodenShield.Stats.addCritRating(2)
WornWoodenShield.Stats.addIntellect(5)
export let PrimativeMantle = std.Items.load(154)
PrimativeMantle.Quality.setWhite()
PrimativeMantle.Stats.addSpellPower(1)
PrimativeMantle.Stats.addCritRating(1)
PrimativeMantle.Stats.addIntellect(2)
export let PrimativeKilt = std.Items.load(153)
PrimativeKilt.Quality.setWhite()
PrimativeKilt.Stats.addSpellPower(2)
PrimativeKilt.Stats.addCritRating(1)
PrimativeKilt.Stats.addIntellect(1)
PrimativeKilt.Stats.addStamina(1)
//Mage Starting Items
export let BentStaff = std.Items.load(35)
BentStaff.DisplayInfo.Models.clearAll()
BentStaff.DisplayInfo.copyFrom(43927)
BentStaff.Quality.setWhite()
BentStaff.Stats.addSpellPower(12)
BentStaff.Stats.addCritRating(7)
BentStaff.Stats.addIntellect(5)
export let ApprenticeRobe = std.Items.load(6140)
ApprenticeRobe.Quality.setWhite()
ApprenticeRobe.Stats.addSpellPower(2)
ApprenticeRobe.Stats.addCritRating(1)
ApprenticeRobe.Stats.addIntellect(1)
ApprenticeRobe.Stats.addStamina(1)
export let ApprenticePants = std.Items.load(1395)
ApprenticePants.Quality.setWhite()
ApprenticePants.Stats.addSpellPower(4)
ApprenticePants.Stats.addCritRating(2)
export let ApprenticeBoots = std.Items.load(55)
ApprenticeBoots.Quality.setWhite()
ApprenticeBoots.Stats.addSpellPower(2)
ApprenticeBoots.Stats.addIntellect(2)
ApprenticeBoots.Stats.addStamina(2)























//Starting Vendor Items
export let LargeRoundShield = std.Items.load(2129)
LargeRoundShield.Quality.setWhite()
LargeRoundShield.Stats.addStamina(2)
LargeRoundShield.Stats.addStrength(1)
export let TarnishedChainVest = std.Items.load(2379)
TarnishedChainVest.Quality.setWhite()
TarnishedChainVest.Stats.addStamina(3)
TarnishedChainVest.Stats.addAgility(1)
TarnishedChainVest.Stats.addIntellect(1)
export let TarnishedChainBelt = std.Items.load(2380)
TarnishedChainBelt.Quality.setWhite()
TarnishedChainBelt.Stats.addStamina(1)
export let TarnishedChainLeggings = std.Items.load(2381)
TarnishedChainLeggings.Quality.setWhite()
TarnishedChainLeggings.Stats.addSpellPower(4)
TarnishedChainLeggings.Stats.addAttackPower(3)
export let TarnishedChainBoots = std.Items.load(2383)
TarnishedChainBoots.Quality.setWhite()
TarnishedChainBoots.Stats.addStamina(1)
export let TarnishedChainBracers = std.Items.load(2384)
TarnishedChainBracers.Quality.setWhite()
TarnishedChainBracers.Stats.addIntellect(1)
TarnishedChainBracers.Stats.addAgility(1)
export let TarnishedChainGloves = std.Items.load(2385)
TarnishedChainGloves.Quality.setWhite()
TarnishedChainGloves.Stats.addStamina(2)
TarnishedChainGloves.Stats.addIntellect(1)
TarnishedChainGloves.Stats.addSpellPower(2)
export let SmallShield = std.Items.load(17184)
SmallShield.Quality.setWhite()
SmallShield.Stats.addStamina(2)
SmallShield.Stats.addIntellect(1)
export let BastardSword = std.Items.load(1194)
BastardSword.Damage.clearAll()
BastardSword.Damage.addPhysical(10,14)
BastardSword.Quality.setWhite()
BastardSword.Stats.addStamina(2)
BastardSword.Stats.addStrength(2)
BastardSword.Stats.addAttackPower(5)
export let Club = std.Items.load(2130)
Club.Damage.clearAll()
Club.Damage.addPhysical(4,6)
Club.Quality.setWhite()
Club.Stats.addStamina(1)
Club.Stats.addStrength(1)
Club.Stats.addAttackPower(2)
export let Shortsword = std.Items.load(2131)
Shortsword.Damage.clearAll()
Shortsword.Damage.addPhysical(4,6)
Shortsword.Quality.setWhite()
Shortsword.Stats.addStamina(1)
Shortsword.Stats.addStrength(1)
Shortsword.Stats.addAgility(1)
export let ShortStaff = std.Items.load(2132)
ShortStaff.Damage.clearAll()
ShortStaff.Damage.addPhysical(1,3)
ShortStaff.Quality.setWhite()
ShortStaff.Stats.addStamina(3)
ShortStaff.Stats.addIntellect(5)
ShortStaff.Stats.addSpellPower(7)
export let HandAxe = std.Items.load(2134)
HandAxe.Damage.clearAll()
HandAxe.Damage.addPhysical(4,6)
HandAxe.Quality.setWhite()
HandAxe.Stats.addStamina(1)
HandAxe.Stats.addStrength(2)
HandAxe.Stats.addAttackPower(3)
export let Dirk = std.Items.load(2139)
Dirk.Damage.clearAll()
Dirk.Damage.addPhysical(4,6)
Dirk.Quality.setWhite()
Dirk.Stats.addStamina(1)
Dirk.Stats.addAgility(2)
Dirk.Stats.addCritRating(4)
Dirk.Stats.addAttackPower(4)
export let BroadAxe = std.Items.load(2479)
BroadAxe.Damage.clearAll()
BroadAxe.Damage.addPhysical(7,16)
BroadAxe.Quality.setWhite()
BroadAxe.Stats.addStamina(3)
BroadAxe.Stats.addStrength(1)
BroadAxe.Stats.addAttackPower(6)
export let LargeClub = std.Items.load(2480)
LargeClub.Damage.clearAll()
LargeClub.Damage.addPhysical(5,20)
LargeClub.Quality.setWhite()
LargeClub.Stats.addAgility(4)
LargeClub.Stats.addAttackPower(10)
export let ThinClothArmor = std.Items.load(2121)
ThinClothArmor.Quality.setWhite()
ThinClothArmor.Stats.addStamina(3)
ThinClothArmor.Stats.addIntellect(2)
export let ThinClothBelt = std.Items.load(3599)
ThinClothBelt.Quality.setWhite()
ThinClothBelt.Stats.addIntellect(2)
export let ThinClothPants = std.Items.load(2120)
ThinClothPants.Quality.setWhite()
ThinClothPants.Stats.addSpellPower(5)
ThinClothPants.Stats.addIntellect(2)
export let ThinClothShoes = std.Items.load(2117)
ThinClothShoes.Quality.setWhite()
ThinClothShoes.Stats.addSpellPower(2)
export let ThinClothBracers = std.Items.load(3600)
ThinClothBracers.Quality.setWhite()
ThinClothBracers.Stats.addIntellect(1)
ThinClothBracers.Stats.addSpellPower(2)
export let ThinClothGloves = std.Items.load(2119)
ThinClothGloves.Quality.setWhite()
ThinClothGloves.Stats.addStamina(1)
ThinClothGloves.Stats.addIntellect(3)
ThinClothGloves.Stats.addSpellPower(4)
export let CrackedLeatherVest = std.Items.load(2127)
CrackedLeatherVest.Quality.setWhite()
CrackedLeatherVest.Stats.addStamina(3)
CrackedLeatherVest.Stats.addAgility(1)
CrackedLeatherVest.Stats.addAttackPower(1)
export let CrackedLeatherBelt = std.Items.load(2122)
CrackedLeatherBelt.Quality.setWhite()
CrackedLeatherBelt.Stats.addAttackPower(2)
export let CrackedLeatherPants = std.Items.load(2126)
CrackedLeatherPants.Quality.setWhite()
CrackedLeatherPants.Stats.addAttackPower(4)
CrackedLeatherPants.Stats.addAgility(3)
export let CrackedLeatherBoots = std.Items.load(2123)
CrackedLeatherBoots.Quality.setWhite()
CrackedLeatherBoots.Stats.addAttackPower(3)
export let CrackedLeatherBracers = std.Items.load(2124)
CrackedLeatherBracers.Quality.setWhite()
CrackedLeatherBracers.Stats.addStamina(2)
CrackedLeatherBracers.Stats.addAgility(1)
export let CrackedLeatherGloves = std.Items.load(2125)
CrackedLeatherGloves.Quality.setWhite()
CrackedLeatherGloves.Stats.addStamina(2)
CrackedLeatherGloves.Stats.addAgility(1)
CrackedLeatherGloves.Stats.addAttackPower(2)