import { MODNAME } from "quests-mod"
import { std } from "../../../tswow-stdlib/datascripts/build/tswow-stdlib-data"

export let BlazingRapier = std.Items.create(MODNAME,'blazingrapier',12777)
BlazingRapier.Quality.setGreen()
export let WickedMithrilBlade = std.Items.create(MODNAME,'wickedmithrilblade',7943)
WickedMithrilBlade.Quality.setGreen()
export let SearingGoldenBlade = std.Items.create(MODNAME,'searinggoldenblade',12260)
SearingGoldenBlade.Quality.setGreen()
export let BuzzSaw = std.Items.create(MODNAME,'buzzsaw',1937)
BuzzSaw.Quality.setGreen()
export let BuzzerBlade = std.Items.create(MODNAME,'buzzerblade',2169)
BuzzerBlade.Quality.setGreen()
export let Rockslicer = std.Items.create(MODNAME,'rockslicer',872)
Rockslicer.Quality.setGreen()
export let RhahkZorsHammer = std.Items.create(MODNAME,'rhahkzorshammer',5187)
RhahkZorsHammer.Name.enGB.set('Smashing Hammer')
RhahkZorsHammer.Quality.setGreen()
export let GoldplatedBuckler = std.Items.create(MODNAME,'goldplatedbuckler',5443)
GoldplatedBuckler.Quality.setGreen()
export let EmberstoneStaff = std.Items.create(MODNAME,'emberstonestaff',5201)
EmberstoneStaff.Quality.setGreen()
export let ImpalingHarpoon = std.Items.create(MODNAME,'impalingharpoon',5200)
ImpalingHarpoon.Quality.setGreen()
export let ThiefsBlade = std.Items.create(MODNAME,'thiefsblade',5192)
ThiefsBlade.Quality.setGreen()
export let SmitesReaver = std.Items.create(MODNAME,'smitesreaver',5196)
SmitesReaver.Name.enGB.set('The Reaver')
SmitesReaver.Quality.setGreen()
export let SmitesMightyHammer = std.Items.create(MODNAME,'smitesmightyhammer',7230)
SmitesMightyHammer.Name.enGB.set('Mighty Hammer')
SmitesMightyHammer.Quality.setGreen()
export let CookiesTenderizer = std.Items.create(MODNAME,'cookiestenderizer',5197)
CookiesTenderizer.Name.enGB.set('Meat Mallet')
CookiesTenderizer.Quality.setGreen()
export let CookiesStirringRod = std.Items.create(MODNAME,'cookiesstirringrod',5198)
CookiesStirringRod.Name.enGB.set('Bent Stick')
CookiesStirringRod.Quality.setGreen()
export let IronKnuckles = std.Items.create(MODNAME,'ironknuckles',2942)
IronKnuckles.Quality.setGreen()
export let PrisonShank = std.Items.create(MODNAME,'prisonshank',2941)
PrisonShank.Name.enGB.set('Rusted Shank')
PrisonShank.Quality.setGreen()
export let KamsWalkingStick = std.Items.create(MODNAME,'kamswalkingstick',2280)
KamsWalkingStick.Quality.setGreen()
export let SerpentsKiss = std.Items.create(MODNAME,'serpentskiss',5426)
SerpentsKiss.Name.enGB.set('Petrified Cobra')
SerpentsKiss.Quality.setGreen()
export let KreshsBack = std.Items.create(MODNAME,'kreshsback',13245)
KreshsBack.Name.enGB.set('Turtle Shell')
KreshsBack.Quality.setGreen()
export let WornTurtleShellShield = std.Items.create(MODNAME,'wornturtleshellshield',6447)
WornTurtleShellShield.Quality.setGreen()
export let SerpentsShoulders = std.Items.create(MODNAME,'serpentsshoulders',5404)
SerpentsShoulders.Name.enGB.set('Gilded Leather Spaulders')
SerpentsShoulders.Quality.setGreen()
export let BoahnsFang = std.Items.create(MODNAME,'boahnsfang',5423)
BoahnsFang.Quality.setGreen()
export let ArmoroftheFang = std.Items.create(MODNAME,'armorofthefang',6473)
ArmoroftheFang.Name.enGB.set('Gilded Leather Armor')
ArmoroftheFang.Quality.setGreen()
export let LeggingsoftheFang = std.Items.create(MODNAME,'leggingsofthefang',10410)
LeggingsoftheFang.Name.enGB.set('Gilded Leather Leggings')
LeggingsoftheFang.Quality.setGreen()
export let FootpadsoftheFang = std.Items.create(MODNAME,'footpadsofthefang',10411)
FootpadsoftheFang.Name.enGB.set('Gilded Leather Footpads')
FootpadsoftheFang.Quality.setGreen()
export let BeltoftheFang = std.Items.create(MODNAME,'beltofthefang',10412)
BeltoftheFang.Name.enGB.set('Gilded Leather Belt')
BeltoftheFang.Quality.setGreen()
export let GlovesoftheFang = std.Items.create(MODNAME,'glovesofthefang',10413)
GlovesoftheFang.Name.enGB.set('Gilded Leather Gloves')
GlovesoftheFang.Quality.setGreen()
export let StaffofNobles = std.Items.create(MODNAME,'staffofnobles',10413)
StaffofNobles.Quality.setGreen()
export let InfernalTricksterLeggings = std.Items.create(MODNAME,'infernaltricksterleggings',17754)
InfernalTricksterLeggings.Quality.setGreen()
export let PhytoskinSpaulders = std.Items.create(MODNAME,'phytoskinspaulders',17749)
PhytoskinSpaulders.Quality.setGreen()
export let BladeofEternalDarkness = std.Items.create(MODNAME,'bladeofeternaldarkness',17780)
BladeofEternalDarkness.Quality.setGreen()
export let GatorbiteAxe = std.Items.create(MODNAME,'gatorbiteaxe',17780)
GatorbiteAxe.Quality.setGreen()
export let FrightskullShaft = std.Items.create(MODNAME,'frightskullshaft',17780)
FrightskullShaft.Quality.setGreen()
export let SkullforgeReaver = std.Items.create(MODNAME,'skullforgereaver',17780)
SkullforgeReaver.Quality.setGreen()
export let RunebladeofBaronRivendare = std.Items.create(MODNAME,'runebladeofbaronrivendare',17780)
RunebladeofBaronRivendare.Quality.setBlue()
export let BladeoftheWretched = std.Items.create(MODNAME,'bladeofthewretched',17780)
BladeoftheWretched.Quality.setGreen()
