import { MODNAME } from "quests-mod"
import { std } from "tswow-stdlib"

export let SmallRedPouch = std.Items.create(MODNAME,'smallredpouch',805)
SmallRedPouch.Quality.setWhite()
SmallRedPouch.ContainerSlots.set(6)
export let SmallBluePouch = std.Items.create(MODNAME,'smallbluepouch',828)
SmallBluePouch.Quality.setWhite()
SmallBluePouch.ContainerSlots.set(6)
export let SmallBlackPouch = std.Items.create(MODNAME,'smallblackpouch',5571)
SmallBlackPouch.Quality.setWhite()
SmallBlackPouch.ContainerSlots.set(6)
export let SmallGreenPouch = std.Items.create(MODNAME,'smallgreenpouch',5572)
SmallGreenPouch.Quality.setWhite()
SmallGreenPouch.ContainerSlots.set(6)
export let BrownLeatherSatchel = std.Items.create(MODNAME,'brownleathersatchel',4498)
BrownLeatherSatchel.Quality.setWhite()
BrownLeatherSatchel.ContainerSlots.set(8)

export let DarnassianBleu = std.Items.create(MODNAME,'darnassianbleu',2070)
DarnassianBleu.Quality.setWhite()
export let ShinyRedApple = std.Items.create(MODNAME,'shinyredapple',4536)
ShinyRedApple.Quality.setWhite()
export let RefreshingSpringWater = std.Items.create(MODNAME,'refreshingspringwater',159)
RefreshingSpringWater.Quality.setWhite()

export let Dirk = std.Items.create(MODNAME,'dirk',159)
Dirk.Quality.setWhite()
export let TornNote = std.Items.create(MODNAME,'tornnote',159)
TornNote.Quality.setWhite()

export let MeltedCandle = std.Items.create(MODNAME,'meltedcandle',755)
MeltedCandle.Quality.setWhite()
export let LargeCandle = std.Items.create(MODNAME,'largecandle',772)
LargeCandle.Quality.setWhite()
export let MagicCandle = std.Items.create(MODNAME,'magiccandle',1399)
MagicCandle.Quality.setWhite()
export let BladedPickaxe = std.Items.create(MODNAME,'bladedpickaxe',1399)
BladedPickaxe.Quality.setWhite()


export let BlazingRapier = std.Items.create(MODNAME,'blazingrapier',12777)
BlazingRapier.Quality.setGreen()
export let WickedMithrilBlade = std.Items.create(MODNAME,'wickedmithrilblade',7943)
WickedMithrilBlade.Quality.setGreen()
export let SearingGoldenBlade = std.Items.create(MODNAME,'searinggoldenblade',12260)
SearingGoldenBlade.Quality.setGreen()
export let BuzzSaw = std.Items.create(MODNAME,'buzzsaw',1937)
BuzzSaw.Quality.setGreen()
export let BuzzerBlade = std.Items.create(MODNAME,'buzzerblade',2169)
BuzzerBlade.Quality.setGreen()
export let Rockslicer = std.Items.create(MODNAME,'rockslicer',872)
Rockslicer.Quality.setGreen()
export let RhahkZorsHammer = std.Items.create(MODNAME,'rhahkzorshammer',5187)
RhahkZorsHammer.Name.enGB.set('Smashing Hammer')
RhahkZorsHammer.Quality.setGreen()
export let GoldplatedBuckler = std.Items.create(MODNAME,'goldplatedbuckler',5443)
GoldplatedBuckler.Quality.setGreen()
export let EmberstoneStaff = std.Items.create(MODNAME,'emberstonestaff',5201)
EmberstoneStaff.Quality.setGreen()
export let ImpalingHarpoon = std.Items.create(MODNAME,'impalingharpoon',5200)
ImpalingHarpoon.Quality.setGreen()
export let ThiefsBlade = std.Items.create(MODNAME,'thiefsblade',5192)
ThiefsBlade.Quality.setGreen()
export let SmitesReaver = std.Items.create(MODNAME,'smitesreaver',5196)
SmitesReaver.Name.enGB.set('The Reaver')
SmitesReaver.Quality.setGreen()
export let SmitesMightyHammer = std.Items.create(MODNAME,'smitesmightyhammer',7230)
SmitesMightyHammer.Name.enGB.set('Mighty Hammer')
SmitesMightyHammer.Quality.setGreen()
export let CookiesTenderizer = std.Items.create(MODNAME,'cookiestenderizer',5197)
CookiesTenderizer.Name.enGB.set('Meat Mallet')
CookiesTenderizer.Quality.setGreen()
export let CookiesStirringRod = std.Items.create(MODNAME,'cookiesstirringrod',5198)
CookiesStirringRod.Name.enGB.set('Bent Stick')
CookiesStirringRod.Quality.setGreen()
export let IronKnuckles = std.Items.create(MODNAME,'ironknuckles',2942)
IronKnuckles.Quality.setGreen()
export let PrisonShank = std.Items.create(MODNAME,'prisonshank',2941)
PrisonShank.Name.enGB.set('Rusted Shank')
PrisonShank.Quality.setGreen()
export let KamsWalkingStick = std.Items.create(MODNAME,'kamswalkingstick',2280)
KamsWalkingStick.Quality.setGreen()
export let SerpentsKiss = std.Items.create(MODNAME,'serpentskiss',5426)
SerpentsKiss.Name.enGB.set('Petrified Cobra')
SerpentsKiss.Quality.setGreen()
export let KreshsBack = std.Items.create(MODNAME,'kreshsback',13245)
KreshsBack.Name.enGB.set('Turtle Shell')
KreshsBack.Quality.setGreen()
export let WornTurtleShellShield = std.Items.create(MODNAME,'wornturtleshellshield',6447)
WornTurtleShellShield.Quality.setGreen()
export let SerpentsShoulders = std.Items.create(MODNAME,'serpentsshoulders',5404)
SerpentsShoulders.Name.enGB.set('Gilded Leather Spaulders')
SerpentsShoulders.Quality.setGreen()
export let BoahnsFang = std.Items.create(MODNAME,'boahnsfang',5423)
BoahnsFang.Quality.setGreen()
export let ArmoroftheFang = std.Items.create(MODNAME,'armorofthefang',6473)
ArmoroftheFang.Name.enGB.set('Gilded Leather Armor')
ArmoroftheFang.Quality.setGreen()
export let LeggingsoftheFang = std.Items.create(MODNAME,'leggingsofthefang',10410)
LeggingsoftheFang.Name.enGB.set('Gilded Leather Leggings')
LeggingsoftheFang.Quality.setGreen()
export let FootpadsoftheFang = std.Items.create(MODNAME,'footpadsofthefang',10411)
FootpadsoftheFang.Name.enGB.set('Gilded Leather Footpads')
FootpadsoftheFang.Quality.setGreen()
export let BeltoftheFang = std.Items.create(MODNAME,'beltofthefang',10412)
BeltoftheFang.Name.enGB.set('Gilded Leather Belt')
BeltoftheFang.Quality.setGreen()
export let GlovesoftheFang = std.Items.create(MODNAME,'glovesofthefang',10413)
GlovesoftheFang.Name.enGB.set('Gilded Leather Gloves')
GlovesoftheFang.Quality.setGreen()
export let StaffofNobles = std.Items.create(MODNAME,'staffofnobles',10413)
StaffofNobles.Quality.setGreen()
export let InfernalTricksterLeggings = std.Items.create(MODNAME,'infernaltricksterleggings',17754)
InfernalTricksterLeggings.Quality.setGreen()
export let PhytoskinSpaulders = std.Items.create(MODNAME,'phytoskinspaulders',17749)
PhytoskinSpaulders.Quality.setGreen()
export let BladeofEternalDarkness = std.Items.create(MODNAME,'bladeofeternaldarkness',17780)
BladeofEternalDarkness.Quality.setGreen()
export let GatorbiteAxe = std.Items.create(MODNAME,'gatorbiteaxe',17780)
GatorbiteAxe.Quality.setGreen()
export let FrightskullShaft = std.Items.create(MODNAME,'frightskullshaft',17780)
FrightskullShaft.Quality.setGreen()
export let SkullforgeReaver = std.Items.create(MODNAME,'skullforgereaver',17780)
SkullforgeReaver.Quality.setGreen()
export let RunebladeofBaronRivendare = std.Items.create(MODNAME,'runebladeofbaronrivendare',17780)
RunebladeofBaronRivendare.Quality.setBlue()
export let BladeoftheWretched = std.Items.create(MODNAME,'bladeofthewretched',17780)
BladeoftheWretched.Quality.setGreen()


export let FangoftheCrystalSpider = std.Items.create(MODNAME,'fangofthecrystalspider',13218)
FangoftheCrystalSpider.Quality.setBlue()
export let GoblinDragonGun = std.Items.create(MODNAME,'goblindragongun',13183)
GoblinDragonGun.Quality.setBlue()
export let DarkwaterTalwar = std.Items.create(MODNAME,'darkwatertalwar',11121)
DarkwaterTalwar.Quality.setBlue()
export let BiteofSerrakis = std.Items.create(MODNAME,'biteofserrakis',6904)
BiteofSerrakis.Quality.setBlue()
export let Grimclaw = std.Items.create(MODNAME,'grimclaw',1481)
Grimclaw.Quality.setBlue()
export let Shadowfang = std.Items.create(MODNAME,'shadowfang',1482)
Shadowfang.Quality.setBlue()
export let StrikeoftheHydra = std.Items.create(MODNAME,'strikeofthehydra',6909)
StrikeoftheHydra.Quality.setBlue()
export let GalgannsFireblaster = std.Items.create(MODNAME,'galgannsfireblaster',9412)
GalgannsFireblaster.Quality.setBlue()
export let GalgannsFirehammer = std.Items.create(MODNAME,'galgannsfirehammer',9419)
GalgannsFirehammer.Quality.setBlue()
export let RagingBerserkersHelm = std.Items.create(MODNAME,'ragingberserkershelm',7719)
RagingBerserkersHelm.Quality.setBlue()
export let HerodsShoulder = std.Items.create(MODNAME,'herodsshoulder',7718)
HerodsShoulder.Quality.setBlue()
export let ScarletLeggings = std.Items.create(MODNAME,'scarletleggings',10330)
ScarletLeggings.Quality.setBlue()
export let DeadmansHand = std.Items.create(MODNAME,'deadmanshand',34227)
DeadmansHand.Quality.setBlue()
export let RobeofDoan = std.Items.create(MODNAME,'robeofdoan',7711)
RobeofDoan.Quality.setBlue()
export let MantleofDoan = std.Items.create(MODNAME,'mantleofdoan',7712)
MantleofDoan.Quality.setBlue()
export let SavageGladiatorChain = std.Items.create(MODNAME,'savagegladiatorchain',11726)
SavageGladiatorChain.Quality.setBlue()
export let SavageGladiatorLeggings = std.Items.create(MODNAME,'savagegladiatorleggings',11728)
SavageGladiatorLeggings.Quality.setBlue()
export let SavageGladiatorHelm = std.Items.create(MODNAME,'savagegladiatorhelm',11729)
SavageGladiatorHelm.Quality.setBlue()
export let SavageGladiatorGrips = std.Items.create(MODNAME,'savagegladiatorgrips',11730)
SavageGladiatorGrips.Quality.setBlue()
export let SavageGladiatorGreaves = std.Items.create(MODNAME,'savagegladiatorgreaves',11731)
SavageGladiatorGreaves.Quality.setBlue()
export let DarkIronPulverizer = std.Items.create(MODNAME,'darkironpulverizer',11608)
DarkIronPulverizer.Quality.setBlue()
export let IronweaveRobe = std.Items.create(MODNAME,'ironweaverobe',22301)
IronweaveRobe.Quality.setBlue()
export let IronweaveCowl = std.Items.create(MODNAME,'ironweavecowl',22302)
IronweaveCowl.Quality.setBlue()
export let IronweavePants = std.Items.create(MODNAME,'ironweavepants',22303)
IronweavePants.Quality.setBlue()
export let IronweaveGloves = std.Items.create(MODNAME,'ironweavegloves',22304)
IronweaveGloves.Quality.setBlue()
export let IronweaveMantle = std.Items.create(MODNAME,'ironweavemantle',22305)
IronweaveMantle.Quality.setBlue()
export let IronweaveBelt = std.Items.create(MODNAME,'ironweavebelt',22306)
IronweaveBelt.Quality.setBlue()
export let IronweaveBoots = std.Items.create(MODNAME,'ironweaveboots',22311)
IronweaveBoots.Quality.setBlue()
export let IronweaveBracers = std.Items.create(MODNAME,'ironweavebracers',22313)
IronweaveBracers.Quality.setBlue()
export let WraithScythe = std.Items.create(MODNAME,'wraithscythe',11920)
WraithScythe.Quality.setBlue()
export let ForceofWill = std.Items.create(MODNAME,'forceofwill',11810)
ForceofWill.Quality.setBlue()
export let LordGeneralsSword = std.Items.create(MODNAME,'lordgeneralssword',11817)
LordGeneralsSword.Quality.setBlue()
export let Naglering = std.Items.create(MODNAME,'naglering',11669)
Naglering.Quality.setBlue()
export let FlameWrath = std.Items.create(MODNAME,'flamewrath',11809)
FlameWrath.Quality.setBlue()
export let BurstofKnowledge = std.Items.create(MODNAME,'burstofknowledge',11832)
BurstofKnowledge.Quality.setBlue()
export let CircleofFlame = std.Items.create(MODNAME,'circleofflame',11808)
CircleofFlame.Quality.setBlue()

export let DazzlingLongsword = std.Items.create(MODNAME,'dazzlinglongsword',869)
DazzlingLongsword.Quality.setPurple()
export let Nightblade = std.Items.create(MODNAME,'nightblade',1982)
Nightblade.Quality.setPurple()
export let FieryWarAxe = std.Items.create(MODNAME,'fierywaraxe',870)
FieryWarAxe.Quality.setPurple()
export let ArdentCustodian = std.Items.create(MODNAME,'ardentcustodian',868)
ArdentCustodian.Quality.setPurple()
export let StaffofJordan = std.Items.create(MODNAME,'staffofjordan',873)
StaffofJordan.Quality.setPurple()
export let TheGreenTower = std.Items.create(MODNAME,'thegreentower',1204)
TheGreenTower.Quality.setPurple()
export let BowofSearingArrows = std.Items.create(MODNAME,'bowofsearingarrows',2825)
BowofSearingArrows.Quality.setPurple()
export let UnderworldBand = std.Items.create(MODNAME,'underworldband',1980)
UnderworldBand.Quality.setPurple()
export let GutRipper = std.Items.create(MODNAME,'gutripper',2164)
GutRipper.Quality.setPurple()
export let Ironfoe = std.Items.create(MODNAME,'ironfoe',11684)
Ironfoe.Quality.setPurple()
export let EskhandarsRightClaw = std.Items.create(MODNAME,'eskhandarsrightclaw',18203)
EskhandarsRightClaw.Quality.setPurple()
export let EskhandarsLeftClaw = std.Items.create(MODNAME,'eskhandarsleftclaw',18202)
EskhandarsLeftClaw.Quality.setPurple()

export let FineLeatherBoots = std.Items.create(MODNAME,'fineleatherboots',2307)
FineLeatherBoots.Quality.setGreen()
export let FineLeatherCloak = std.Items.create(MODNAME,'fineleathercloak',2308)
FineLeatherCloak.Quality.setGreen()
export let FineLeatherGloves = std.Items.create(MODNAME,'fineleathergloves',2312)
FineLeatherGloves.Quality.setGreen()
export let FineLeatherTunic = std.Items.create(MODNAME,'fineleathertunic',4243)
FineLeatherTunic.Quality.setGreen()
export let FineLeatherBelt = std.Items.create(MODNAME,'fineleatherbelt',4246)
FineLeatherBelt.Quality.setGreen()
export let EmbossedLeatherVest = std.Items.create(MODNAME,'embossedleathervest',2300)
EmbossedLeatherVest.Quality.setGreen()
export let EmbossedLeatherBoots = std.Items.create(MODNAME,'embossedleatherboots',2309)
EmbossedLeatherBoots.Quality.setGreen()
export let EmbossedLeatherCloak = std.Items.create(MODNAME,'embossedleathercloak',2310)
EmbossedLeatherCloak.Quality.setGreen()
export let EmbossedLeatherGloves = std.Items.create(MODNAME,'embossedleathergloves',4239)
EmbossedLeatherGloves.Quality.setGreen()
export let EmbossedLeatherPants = std.Items.create(MODNAME,'embossedleatherpants',4242)
EmbossedLeatherPants.Quality.setGreen()
export let AzureSilkGloves = std.Items.create(MODNAME,'azuresilkgloves',4319)
AzureSilkGloves.Quality.setGreen()
export let AzureSilkVest = std.Items.create(MODNAME,'azuresilkvest',4324)
AzureSilkVest.Quality.setGreen()
export let AzureSilkPants = std.Items.create(MODNAME,'azuresilkpants',7046)
AzureSilkPants.Quality.setGreen()
export let AzureSilkHood = std.Items.create(MODNAME,'azuresilkhood',7048)
AzureSilkHood.Quality.setGreen()
export let AzureSilkBelt = std.Items.create(MODNAME,'azuresilkbelt',7052)
AzureSilkBelt.Quality.setGreen()
export let AzureSilkCloak = std.Items.create(MODNAME,'azuresilkcloak',7053)
AzureSilkCloak.Quality.setGreen()
export let CrimsonSilkBelt = std.Items.create(MODNAME,'crimsonsilkbelt',7055)
CrimsonSilkBelt.Quality.setGreen()
export let CrimsonSilkCloak = std.Items.create(MODNAME,'crimsonsilkcloak',7056)
CrimsonSilkCloak.Quality.setGreen()
export let CrimsonSilkVest = std.Items.create(MODNAME,'crimsonsilkvest',7058)
CrimsonSilkVest.Quality.setGreen()
export let CrimsonSilkShoulders = std.Items.create(MODNAME,'crimsonsilkshoulders',7059)
CrimsonSilkShoulders.Quality.setGreen()
export let CrimsonSilkPantaloons = std.Items.create(MODNAME,'crimsonsilkpantaloons',7062)
CrimsonSilkPantaloons.Quality.setGreen()
export let CrimsonSilkRobe = std.Items.create(MODNAME,'crimsonsilkrobe',7063)
CrimsonSilkRobe.Quality.setGreen()
export let CrimsonSilkGloves = std.Items.create(MODNAME,'crimsonsilkgloves',7064)
CrimsonSilkGloves.Quality.setGreen()
export let SilveredBronzeBreastplate = std.Items.create(MODNAME,'silveredbronzebreastplate',2869)
SilveredBronzeBreastplate.Quality.setGreen()
export let SilveredBronzeShoulders = std.Items.create(MODNAME,'silveredBronzeshoulders',3481)
SilveredBronzeShoulders.Quality.setGreen()
export let SilveredBronzeBoots = std.Items.create(MODNAME,'silveredbronzeboots',3482)
SilveredBronzeBoots.Quality.setGreen()
export let SilveredBronzeGauntlets = std.Items.create(MODNAME,'silveredbronzegauntlets',3483)
SilveredBronzeGauntlets.Quality.setGreen()
export let BarbaricIronShoulders = std.Items.create(MODNAME,'barbaricironshoulders',7913)
BarbaricIronShoulders.Quality.setGreen()
export let BarbaricIronBreastplate = std.Items.create(MODNAME,'barbaricironbreastplate',7914)
BarbaricIronBreastplate.Quality.setGreen()
export let BarbaricIronHelm = std.Items.create(MODNAME,'barbaricironhelm',7915)
BarbaricIronHelm.Quality.setGreen()
export let BarbaricIronBoots = std.Items.create(MODNAME,'barbaricironboots',7916)
BarbaricIronBoots.Quality.setGreen()
export let BarbaricIronGloves = std.Items.create(MODNAME,'barbaricirongloves',7917)
BarbaricIronGloves.Quality.setGreen()

export let MinorManaPotion = std.Items.create(MODNAME,'minormanapotion',2455)
MinorManaPotion.Quality.setWhite()
export let MinorHealingPotion = std.Items.create(MODNAME,'minorhealingpotion',118)
MinorHealingPotion.Quality.setWhite()
export let MinorRejuvenationPotion = std.Items.create(MODNAME,'minorrejuvenationpotion',2456)
MinorRejuvenationPotion.Quality.setWhite()
export let DiscoloredHealingPotion = std.Items.create(MODNAME,'discoloredhealingpotion',4596)
DiscoloredHealingPotion.Quality.setWhite()
export let LesserHealingPotion = std.Items.create(MODNAME,'lesserhealingpotion',858)
LesserHealingPotion.Quality.setWhite()
export let SwiftnessPotion = std.Items.create(MODNAME,'swiftnesspotion',2459)
SwiftnessPotion.Quality.setWhite()
export let RagePotion = std.Items.create(MODNAME,'ragepotion',5631)
RagePotion.Quality.setWhite()
export let SwimSpeedPotion = std.Items.create(MODNAME,'swimspeedpotion',6372)
SwimSpeedPotion.Quality.setWhite()
export let LesserManaPotion = std.Items.create(MODNAME,'lessermanapotion',3385)
LesserManaPotion.Quality.setWhite()

export let ScrollofSpiritVIII = std.Items.create(MODNAME,'scrollofspiritviii',37098)
ScrollofSpiritVIII.Quality.setWhite()
export let ScrollofProtectionVIII = std.Items.create(MODNAME,'scrollofprotectionviii',43468)
ScrollofProtectionVIII.Quality.setWhite()
export let ScrollofAgilityVIII = std.Items.create(MODNAME,'scrollofagilityviii',43464)
ScrollofAgilityVIII.Quality.setWhite()
export let ScrollofIntellectVIII = std.Items.create(MODNAME,'scrollofintellectviii',37092)
ScrollofIntellectVIII.Quality.setWhite()
export let ScrollofStaminaVIII = std.Items.create(MODNAME,'scrollofstaminaviii',37094)
ScrollofStaminaVIII.Quality.setWhite()
export let ScrollofStrengthVIII = std.Items.create(MODNAME,'scrollofstrengthviii',43466)
ScrollofStrengthVIII.Quality.setWhite()
