import { std } from "tswow-stdlib"
import { MODNAME } from "../../../modname"
import { expSpell4 } from "../../../spells/experience-rate-spells"


export let OrbofPower = std.Items.create(MODNAME,'powerorb01',43102)
OrbofPower.Name.enGB.set('Orb of Infinite Power')
OrbofPower.Quality.setPurple()
OrbofPower.MaxStack.set(500)
OrbofPower.Price.set(100000,20000000,1)
OrbofPower.Bonding.setBindsOnPickup()

export let PowerToken = std.Items.load(37711)
PowerToken.Name.enGB.set('Token of Infinite Power')
PowerToken.Description.enGB.set('This token contains incredible power and it can be traded for items that match it\'s esteem.')
PowerToken.Quality.setPurple()

export let ItemReward01 = std.Items.create(MODNAME,'itemreward01',49783)
ItemReward01.RequiredLevel.set(10)
ItemReward01.Quality.setPurple()
export let ItemReward02 = std.Items.create(MODNAME,'itemreward02',50191)
ItemReward02.RequiredLevel.set(10)
ItemReward02.Quality.setPurple()
export let ItemReward03 = std.Items.create(MODNAME,'itemreward03',49790)
ItemReward03.RequiredLevel.set(10)
ItemReward03.Quality.setPurple()
export let ItemReward04 = std.Items.create(MODNAME,'itemreward04',49789)
ItemReward04.RequiredLevel.set(10)
ItemReward04.Quality.setPurple()
export let ItemReward05 = std.Items.create(MODNAME,'itemreward05',49844)
ItemReward05.RequiredLevel.set(10)
ItemReward05.Quality.setPurple()
export let ItemReward06 = std.Items.create(MODNAME,'itemreward06',49839)
ItemReward06.RequiredLevel.set(10)
ItemReward06.Quality.setPurple()

export let ItemReward07 = std.Items.create(MODNAME,'itemreward07',50047)
ItemReward07.RequiredLevel.set(7)
ItemReward07.Quality.setPurple()
ItemReward07.Spells.clearAll()
ItemReward07.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward08 = std.Items.create(MODNAME,'itemreward08',50046)
ItemReward08.RequiredLevel.set(7)
ItemReward08.Quality.setPurple()
ItemReward08.Spells.clearAll()
ItemReward08.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward09 = std.Items.create(MODNAME,'itemreward09',50049)
ItemReward09.RequiredLevel.set(7)
ItemReward09.Quality.setPurple()
ItemReward09.Spells.clearAll()
ItemReward09.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward10 = std.Items.create(MODNAME,'itemreward10',50048)
ItemReward10.RequiredLevel.set(7)
ItemReward10.Quality.setPurple()
ItemReward10.Spells.clearAll()
ItemReward10.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward11 = std.Items.create(MODNAME,'itemreward11',50051)
ItemReward11.RequiredLevel.set(7)
ItemReward11.Quality.setPurple()
ItemReward11.Spells.clearAll()
ItemReward11.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward12 = std.Items.create(MODNAME,'itemreward12',50050)
ItemReward12.RequiredLevel.set(7)
ItemReward12.Quality.setPurple()
ItemReward12.Spells.clearAll()
ItemReward12.Spells.add(expSpell4.ID,0,1,0,0,0,0)
export let ItemReward13 = std.Items.create(MODNAME,'itemreward13',50052)
ItemReward13.RequiredLevel.set(7)
ItemReward13.Quality.setPurple()
ItemReward13.Spells.clearAll()
ItemReward13.Spells.add(expSpell4.ID,0,1,0,0,0,0)