
import { std } from "tswow-stdlib"
import { MODNAME } from "../../modname"
import { SpiritI, ProtectionI, AgilityI, IntellectI, StaminaI, StrengthI } from "./zone-1-item-spells"

export let RavenLordMount = std.Items.load(32768)
RavenLordMount.RequiredLevel.set(3)

export let BoarskinSatchel = std.Items.create(MODNAME,'boarskinsatchel',4498)
BoarskinSatchel.Name.enGB.set('Boar Skin Satchel')
BoarskinSatchel.Quality.setGreen()
BoarskinSatchel.ContainerSlots.set(16)
export let BoarSkin = std.Items.create(MODNAME,'boarskin',2318)
BoarSkin.Name.enGB.set('Boar Skin')
BoarSkin.Quality.setWhite()
BoarSkin.MaxStack.set(9999)
export let DeerSkin = std.Items.create(MODNAME,'deerskin',2318)
DeerSkin.Name.enGB.set('Deer Skin')
DeerSkin.Quality.setGray()
DeerSkin.MaxStack.set(9999)
DeerSkin.DisplayInfo.copyFrom(9591)
export let Teeth = std.Items.create(MODNAME,'teeth',2318)
Teeth.Name.enGB.set('Sharp Tooth')
Teeth.Quality.setGray()
Teeth.MaxStack.set(9999)
Teeth.DisplayInfo.copyFrom(7073)
export let RabbitSkin = std.Items.create(MODNAME,'rabbitskin',2318)
RabbitSkin.Name.enGB.set('Rabbit Skin')
RabbitSkin.Quality.setGray()
RabbitSkin.MaxStack.set(9999)
RabbitSkin.DisplayInfo.copyFrom(3862)

export let Silverleaf = std.Items.create(MODNAME,'silverleaf',765)
Silverleaf.Quality.setWhite()
Silverleaf.MaxStack.set(500)
export let Earthroot = std.Items.create(MODNAME,'earthroot',2449)
Earthroot.Quality.setWhite()
Earthroot.MaxStack.set(500)
export let WildSteelbloom = std.Items.create(MODNAME,'wildsteelbloom',3355)
WildSteelbloom.Quality.setWhite()
WildSteelbloom.MaxStack.set(500)
export let Mageroyal = std.Items.create(MODNAME,'mageroyal',785)
Mageroyal.Quality.setWhite()
Mageroyal.MaxStack.set(500)
export let Peacebloom = std.Items.create(MODNAME,'peacebloom',2447)
Peacebloom.Quality.setWhite()
Peacebloom.MaxStack.set(500)

export let SmallRedPouch = std.Items.create(MODNAME,'smallredpouch',805)
SmallRedPouch.Quality.setWhite()
SmallRedPouch.ContainerSlots.set(6)
export let SmallBluePouch = std.Items.create(MODNAME,'smallbluepouch',828)
SmallBluePouch.Quality.setWhite()
SmallBluePouch.ContainerSlots.set(6)
export let SmallBlackPouch = std.Items.create(MODNAME,'smallblackpouch',5571)
SmallBlackPouch.Quality.setWhite()
SmallBlackPouch.ContainerSlots.set(6)
export let SmallGreenPouch = std.Items.create(MODNAME,'smallgreenpouch',5572)
SmallGreenPouch.Quality.setWhite()
SmallGreenPouch.ContainerSlots.set(6)
export let BrownLeatherSatchel = std.Items.create(MODNAME,'brownleathersatchel',4498)
BrownLeatherSatchel.Quality.setWhite()
BrownLeatherSatchel.ContainerSlots.set(8)

export let DarnassianBleu = std.Items.create(MODNAME,'darnassianbleu',2070)
DarnassianBleu.Quality.setWhite()
export let ShinyRedApple = std.Items.create(MODNAME,'shinyredapple',4536)
ShinyRedApple.Quality.setWhite()
export let RefreshingSpringWater = std.Items.create(MODNAME,'refreshingspringwater',159)
RefreshingSpringWater.Quality.setWhite()

export let Dirk = std.Items.create(MODNAME,'dirk',159)
Dirk.Quality.setWhite()
export let TornNote = std.Items.create(MODNAME,'tornnote',159)
TornNote.Quality.setWhite()

export let MeltedCandle = std.Items.create(MODNAME,'meltedcandle',755)
MeltedCandle.Quality.setWhite()
export let LargeCandle = std.Items.create(MODNAME,'largecandle',772)
LargeCandle.Quality.setWhite()
export let MagicCandle = std.Items.create(MODNAME,'magiccandle',1399)
MagicCandle.Quality.setWhite()
export let BladedPickaxe = std.Items.create(MODNAME,'bladedpickaxe',1399)
BladedPickaxe.Quality.setGreen()


export let BlazingRapier = std.Items.create(MODNAME,'blazingrapier',12777)
BlazingRapier.Quality.setGreen()
BlazingRapier.RequiredLevel.set(3)
export let WickedMithrilBlade = std.Items.create(MODNAME,'wickedmithrilblade',7943)
WickedMithrilBlade.Quality.setGreen()
WickedMithrilBlade.RequiredLevel.set(3)
export let SearingGoldenBlade = std.Items.create(MODNAME,'searinggoldenblade',12260)
SearingGoldenBlade.Quality.setGreen()
SearingGoldenBlade.RequiredLevel.set(3)
export let BuzzSaw = std.Items.create(MODNAME,'buzzsaw',1937)
BuzzSaw.Quality.setGreen()
BuzzSaw.RequiredLevel.set(3)
export let BuzzerBlade = std.Items.create(MODNAME,'buzzerblade',2169)
BuzzerBlade.Quality.setGreen()
BuzzerBlade.RequiredLevel.set(3)
export let Rockslicer = std.Items.create(MODNAME,'rockslicer',872)
Rockslicer.Quality.setGreen()
Rockslicer.RequiredLevel.set(3)
export let RhahkZorsHammer = std.Items.create(MODNAME,'rhahkzorshammer',5187)
RhahkZorsHammer.Name.enGB.set('Smashing Hammer')
RhahkZorsHammer.Quality.setGreen()
RhahkZorsHammer.RequiredLevel.set(3)
export let GoldplatedBuckler = std.Items.create(MODNAME,'goldplatedbuckler',5443)
GoldplatedBuckler.Quality.setGreen()
GoldplatedBuckler.RequiredLevel.set(3)
export let EmberstoneStaff = std.Items.create(MODNAME,'emberstonestaff',5201)
EmberstoneStaff.Quality.setGreen()
EmberstoneStaff.RequiredLevel.set(3)
export let ImpalingHarpoon = std.Items.create(MODNAME,'impalingharpoon',5200)
ImpalingHarpoon.Quality.setGreen()
ImpalingHarpoon.RequiredLevel.set(3)
export let ThiefsBlade = std.Items.create(MODNAME,'thiefsblade',5192)
ThiefsBlade.Quality.setGreen()
ThiefsBlade.RequiredLevel.set(3)
export let SmitesReaver = std.Items.create(MODNAME,'smitesreaver',5196)
SmitesReaver.Name.enGB.set('The Reaver')
SmitesReaver.Quality.setGreen()
SmitesReaver.RequiredLevel.set(3)
export let SmitesMightyHammer = std.Items.create(MODNAME,'smitesmightyhammer',7230)
SmitesMightyHammer.Name.enGB.set('Mighty Hammer')
SmitesMightyHammer.Quality.setGreen()
SmitesMightyHammer.RequiredLevel.set(3)
export let CookiesTenderizer = std.Items.create(MODNAME,'cookiestenderizer',5197)
CookiesTenderizer.Name.enGB.set('Meat Mallet')
CookiesTenderizer.Quality.setGreen()
CookiesTenderizer.RequiredLevel.set(3)
export let CookiesStirringRod = std.Items.create(MODNAME,'cookiesstirringrod',5198)
CookiesStirringRod.Name.enGB.set('Bent Stick')
CookiesStirringRod.Quality.setGreen()
CookiesStirringRod.RequiredLevel.set(3)
export let IronKnuckles = std.Items.create(MODNAME,'ironknuckles',2942)
IronKnuckles.Quality.setGreen()
IronKnuckles.RequiredLevel.set(3)
export let PrisonShank = std.Items.create(MODNAME,'prisonshank',2941)
PrisonShank.Name.enGB.set('Rusted Shank')
PrisonShank.Quality.setGreen()
PrisonShank.RequiredLevel.set(3)
export let KamsWalkingStick = std.Items.create(MODNAME,'kamswalkingstick',2280)
KamsWalkingStick.Quality.setGreen()
KamsWalkingStick.RequiredLevel.set(3)
export let SerpentsKiss = std.Items.create(MODNAME,'serpentskiss',5426)
SerpentsKiss.Name.enGB.set('Petrified Cobra')
SerpentsKiss.Quality.setGreen()
SerpentsKiss.RequiredLevel.set(3)
export let KreshsBack = std.Items.create(MODNAME,'kreshsback',13245)
KreshsBack.Name.enGB.set('Turtle Shell')
KreshsBack.Quality.setGreen()
KreshsBack.RequiredLevel.set(3)
export let WornTurtleShellShield = std.Items.create(MODNAME,'wornturtleshellshield',6447)
WornTurtleShellShield.Quality.setGreen()
WornTurtleShellShield.RequiredLevel.set(3)
export let SerpentsShoulders = std.Items.create(MODNAME,'serpentsshoulders',5404)
SerpentsShoulders.Name.enGB.set('Gilded Leather Spaulders')
SerpentsShoulders.Quality.setGreen()
SerpentsShoulders.RequiredLevel.set(3)
export let BoahnsFang = std.Items.create(MODNAME,'boahnsfang',5423)
BoahnsFang.Quality.setGreen()
BoahnsFang.RequiredLevel.set(3)
export let ArmoroftheFang = std.Items.create(MODNAME,'armorofthefang',6473)
ArmoroftheFang.Name.enGB.set('Gilded Leather Armor')
ArmoroftheFang.Quality.setGreen()
ArmoroftheFang.RequiredLevel.set(3)
export let LeggingsoftheFang = std.Items.create(MODNAME,'leggingsofthefang',10410)
LeggingsoftheFang.Name.enGB.set('Gilded Leather Leggings')
LeggingsoftheFang.Quality.setGreen()
LeggingsoftheFang.RequiredLevel.set(3)
export let FootpadsoftheFang = std.Items.create(MODNAME,'footpadsofthefang',10411)
FootpadsoftheFang.Name.enGB.set('Gilded Leather Footpads')
FootpadsoftheFang.Quality.setGreen()
FootpadsoftheFang.RequiredLevel.set(3)
export let BeltoftheFang = std.Items.create(MODNAME,'beltofthefang',10412)
BeltoftheFang.Name.enGB.set('Gilded Leather Belt')
BeltoftheFang.Quality.setGreen()
BeltoftheFang.RequiredLevel.set(3)
export let GlovesoftheFang = std.Items.create(MODNAME,'glovesofthefang',10413)
GlovesoftheFang.Name.enGB.set('Gilded Leather Gloves')
GlovesoftheFang.Quality.setGreen()
GlovesoftheFang.RequiredLevel.set(3)
export let StaffofNobles = std.Items.create(MODNAME,'staffofnobles',10413)
StaffofNobles.Quality.setGreen()
StaffofNobles.RequiredLevel.set(3)
export let InfernalTricksterLeggings = std.Items.create(MODNAME,'infernaltricksterleggings',17754)
InfernalTricksterLeggings.Quality.setGreen()
InfernalTricksterLeggings.RequiredLevel.set(3)
export let PhytoskinSpaulders = std.Items.create(MODNAME,'phytoskinspaulders',17749)
PhytoskinSpaulders.Quality.setGreen()
PhytoskinSpaulders.RequiredLevel.set(3)
export let BladeofEternalDarkness = std.Items.create(MODNAME,'bladeofeternaldarkness',17780)
BladeofEternalDarkness.Quality.setGreen()
BladeofEternalDarkness.RequiredLevel.set(3)
export let GatorbiteAxe = std.Items.create(MODNAME,'gatorbiteaxe',17780)
GatorbiteAxe.Quality.setGreen()
GatorbiteAxe.RequiredLevel.set(3)
export let FrightskullShaft = std.Items.create(MODNAME,'frightskullshaft',17780)
FrightskullShaft.Quality.setGreen()
FrightskullShaft.RequiredLevel.set(3)
export let SkullforgeReaver = std.Items.create(MODNAME,'skullforgereaver',17780)
SkullforgeReaver.Quality.setGreen()
SkullforgeReaver.RequiredLevel.set(3)
export let RunebladeofBaronRivendare = std.Items.create(MODNAME,'runebladeofbaronrivendare',17780)
RunebladeofBaronRivendare.Quality.setBlue()
RunebladeofBaronRivendare.RequiredLevel.set(3)
export let BladeoftheWretched = std.Items.create(MODNAME,'bladeofthewretched',17780)
BladeoftheWretched.Quality.setGreen()
BladeoftheWretched.RequiredLevel.set(3)


export let FangoftheCrystalSpider = std.Items.create(MODNAME,'fangofthecrystalspider',13218)
FangoftheCrystalSpider.Quality.setBlue()
FangoftheCrystalSpider.RequiredLevel.set(3)
export let GoblinDragonGun = std.Items.create(MODNAME,'goblindragongun',13183)
GoblinDragonGun.Quality.setBlue()
GoblinDragonGun.RequiredLevel.set(3)
export let DarkwaterTalwar = std.Items.create(MODNAME,'darkwatertalwar',11121)
DarkwaterTalwar.Quality.setBlue()
DarkwaterTalwar.RequiredLevel.set(3)
export let BiteofSerrakis = std.Items.create(MODNAME,'biteofserrakis',6904)
BiteofSerrakis.Quality.setBlue()
BiteofSerrakis.RequiredLevel.set(3)
export let Grimclaw = std.Items.create(MODNAME,'grimclaw',1481)
Grimclaw.Quality.setBlue()
Grimclaw.RequiredLevel.set(3)
export let Shadowfang = std.Items.create(MODNAME,'shadowfang',1482)
Shadowfang.Quality.setBlue()
Shadowfang.RequiredLevel.set(3)
export let StrikeoftheHydra = std.Items.create(MODNAME,'strikeofthehydra',6909)
StrikeoftheHydra.Quality.setBlue()
StrikeoftheHydra.RequiredLevel.set(3)
export let GalgannsFireblaster = std.Items.create(MODNAME,'galgannsfireblaster',9412)
GalgannsFireblaster.Quality.setBlue()
GalgannsFireblaster.RequiredLevel.set(3)
export let GalgannsFirehammer = std.Items.create(MODNAME,'galgannsfirehammer',9419)
GalgannsFirehammer.Quality.setBlue()
GalgannsFirehammer.RequiredLevel.set(3)
export let RagingBerserkersHelm = std.Items.create(MODNAME,'ragingberserkershelm',7719)
RagingBerserkersHelm.Quality.setBlue()
RagingBerserkersHelm.RequiredLevel.set(3)
export let HerodsShoulder = std.Items.create(MODNAME,'herodsshoulder',7718)
HerodsShoulder.Quality.setBlue()
HerodsShoulder.RequiredLevel.set(3)
export let ScarletLeggings = std.Items.create(MODNAME,'scarletleggings',10330)
ScarletLeggings.Quality.setBlue()
ScarletLeggings.RequiredLevel.set(3)
export let DeadmansHand = std.Items.create(MODNAME,'deadmanshand',34227)
DeadmansHand.Quality.setBlue()
DeadmansHand.RequiredLevel.set(3)
export let RobeofDoan = std.Items.create(MODNAME,'robeofdoan',7711)
RobeofDoan.Quality.setBlue()
RobeofDoan.RequiredLevel.set(3)
export let MantleofDoan = std.Items.create(MODNAME,'mantleofdoan',7712)
MantleofDoan.Quality.setBlue()
MantleofDoan.RequiredLevel.set(3)
export let SavageGladiatorChain = std.Items.create(MODNAME,'savagegladiatorchain',11726)
SavageGladiatorChain.Quality.setBlue()
SavageGladiatorChain.RequiredLevel.set(3)
export let SavageGladiatorLeggings = std.Items.create(MODNAME,'savagegladiatorleggings',11728)
SavageGladiatorLeggings.Quality.setBlue()
SavageGladiatorLeggings.RequiredLevel.set(3)
export let SavageGladiatorHelm = std.Items.create(MODNAME,'savagegladiatorhelm',11729)
SavageGladiatorHelm.Quality.setBlue()
SavageGladiatorHelm.RequiredLevel.set(3)
export let SavageGladiatorGrips = std.Items.create(MODNAME,'savagegladiatorgrips',11730)
SavageGladiatorGrips.Quality.setBlue()
SavageGladiatorGrips.RequiredLevel.set(3)
export let SavageGladiatorGreaves = std.Items.create(MODNAME,'savagegladiatorgreaves',11731)
SavageGladiatorGreaves.Quality.setBlue()
SavageGladiatorGreaves.RequiredLevel.set(3)
export let DarkIronPulverizer = std.Items.create(MODNAME,'darkironpulverizer',11608)
DarkIronPulverizer.Quality.setBlue()
DarkIronPulverizer.RequiredLevel.set(3)
export let IronweaveRobe = std.Items.create(MODNAME,'ironweaverobe',22301)
IronweaveRobe.Quality.setBlue()
IronweaveRobe.RequiredLevel.set(3)
export let IronweaveCowl = std.Items.create(MODNAME,'ironweavecowl',22302)
IronweaveCowl.Quality.setBlue()
IronweaveCowl.RequiredLevel.set(3)
export let IronweavePants = std.Items.create(MODNAME,'ironweavepants',22303)
IronweavePants.Quality.setBlue()
IronweavePants.RequiredLevel.set(3)
export let IronweaveGloves = std.Items.create(MODNAME,'ironweavegloves',22304)
IronweaveGloves.Quality.setBlue()
IronweaveGloves.RequiredLevel.set(3)
export let IronweaveMantle = std.Items.create(MODNAME,'ironweavemantle',22305)
IronweaveMantle.Quality.setBlue()
IronweaveMantle.RequiredLevel.set(3)
export let IronweaveBelt = std.Items.create(MODNAME,'ironweavebelt',22306)
IronweaveBelt.Quality.setBlue()
IronweaveBelt.RequiredLevel.set(3)
export let IronweaveBoots = std.Items.create(MODNAME,'ironweaveboots',22311)
IronweaveBoots.Quality.setBlue()
IronweaveBoots.RequiredLevel.set(3)
export let IronweaveBracers = std.Items.create(MODNAME,'ironweavebracers',22313)
IronweaveBracers.Quality.setBlue()
IronweaveBracers.RequiredLevel.set(3)
export let WraithScythe = std.Items.create(MODNAME,'wraithscythe',11920)
WraithScythe.Quality.setBlue()
WraithScythe.RequiredLevel.set(3)
export let ForceofWill = std.Items.create(MODNAME,'forceofwill',11810)
ForceofWill.Quality.setBlue()
ForceofWill.RequiredLevel.set(3)
export let LordGeneralsSword = std.Items.create(MODNAME,'lordgeneralssword',11817)
LordGeneralsSword.Quality.setBlue()
LordGeneralsSword.RequiredLevel.set(3)
export let Naglering = std.Items.create(MODNAME,'naglering',11669)
Naglering.Quality.setBlue()
Naglering.RequiredLevel.set(3)
export let FlameWrath = std.Items.create(MODNAME,'flamewrath',11809)
FlameWrath.Quality.setBlue()
FlameWrath.RequiredLevel.set(3)
export let BurstofKnowledge = std.Items.create(MODNAME,'burstofknowledge',11832)
BurstofKnowledge.Quality.setBlue()
BurstofKnowledge.RequiredLevel.set(3)
export let CircleofFlame = std.Items.create(MODNAME,'circleofflame',11808)
CircleofFlame.Quality.setBlue()
CircleofFlame.RequiredLevel.set(3)
export let MongooseSword = std.Items.create(MODNAME,'mongoosesword',11817)
MongooseSword.Quality.setBlue()
MongooseSword.Spells.clearAll()
MongooseSword.Spells.add(28093,0,1)
MongooseSword.RequiredLevel.set(3)

export let DazzlingLongsword = std.Items.create(MODNAME,'dazzlinglongsword',869)
DazzlingLongsword.Quality.setPurple()
DazzlingLongsword.RequiredLevel.set(3)
export let Nightblade = std.Items.create(MODNAME,'nightblade',1982)
Nightblade.Quality.setPurple()
Nightblade.RequiredLevel.set(3)
export let FieryWarAxe = std.Items.create(MODNAME,'fierywaraxe',870)
FieryWarAxe.Quality.setPurple()
FieryWarAxe.RequiredLevel.set(3)
export let ArdentCustodian = std.Items.create(MODNAME,'ardentcustodian',868)
ArdentCustodian.Quality.setPurple()
ArdentCustodian.RequiredLevel.set(3)
export let StaffofJordan = std.Items.create(MODNAME,'staffofjordan',873)
StaffofJordan.Quality.setPurple()
StaffofJordan.RequiredLevel.set(3)
export let TheGreenTower = std.Items.create(MODNAME,'thegreentower',1204)
TheGreenTower.Quality.setPurple()
TheGreenTower.RequiredLevel.set(3)
export let BowofSearingArrows = std.Items.create(MODNAME,'bowofsearingarrows',2825)
BowofSearingArrows.Quality.setPurple()
BowofSearingArrows.RequiredLevel.set(3)
export let UnderworldBand = std.Items.create(MODNAME,'underworldband',1980)
UnderworldBand.Quality.setPurple()
UnderworldBand.RequiredLevel.set(3)
export let GutRipper = std.Items.create(MODNAME,'gutripper',2164)
GutRipper.Quality.setPurple()
GutRipper.RequiredLevel.set(3)
export let Ironfoe = std.Items.create(MODNAME,'ironfoe',11684)
Ironfoe.Quality.setPurple()
Ironfoe.RequiredLevel.set(3)
export let EskhandarsRightClaw = std.Items.create(MODNAME,'eskhandarsrightclaw',18203)
EskhandarsRightClaw.Quality.setPurple()
EskhandarsRightClaw.RequiredLevel.set(3)
export let EskhandarsLeftClaw = std.Items.create(MODNAME,'eskhandarsleftclaw',18202)
EskhandarsLeftClaw.Quality.setPurple()
EskhandarsLeftClaw.RequiredLevel.set(3)

export let FineLeatherBoots = std.Items.create(MODNAME,'fineleatherboots',2307)
FineLeatherBoots.Quality.setGreen()
FineLeatherBoots.RequiredLevel.set(3)
export let FineLeatherCloak = std.Items.create(MODNAME,'fineleathercloak',2308)
FineLeatherCloak.Quality.setGreen()
FineLeatherCloak.RequiredLevel.set(3)
export let FineLeatherGloves = std.Items.create(MODNAME,'fineleathergloves',2312)
FineLeatherGloves.Quality.setGreen()
FineLeatherGloves.RequiredLevel.set(3)
export let FineLeatherTunic = std.Items.create(MODNAME,'fineleathertunic',4243)
FineLeatherTunic.Quality.setGreen()
FineLeatherTunic.RequiredLevel.set(3)
export let FineLeatherBelt = std.Items.create(MODNAME,'fineleatherbelt',4246)
FineLeatherBelt.Quality.setGreen()
FineLeatherBelt.RequiredLevel.set(3)
export let EmbossedLeatherVest = std.Items.create(MODNAME,'embossedleathervest',2300)
EmbossedLeatherVest.Quality.setGreen()
EmbossedLeatherVest.RequiredLevel.set(3)
export let EmbossedLeatherBoots = std.Items.create(MODNAME,'embossedleatherboots',2309)
EmbossedLeatherBoots.Quality.setGreen()
EmbossedLeatherBoots.RequiredLevel.set(3)
export let EmbossedLeatherCloak = std.Items.create(MODNAME,'embossedleathercloak',2310)
EmbossedLeatherCloak.Quality.setGreen()
EmbossedLeatherCloak.RequiredLevel.set(3)
export let EmbossedLeatherGloves = std.Items.create(MODNAME,'embossedleathergloves',4239)
EmbossedLeatherGloves.Quality.setGreen()
EmbossedLeatherGloves.RequiredLevel.set(3)
export let EmbossedLeatherPants = std.Items.create(MODNAME,'embossedleatherpants',4242)
EmbossedLeatherPants.Quality.setGreen()
EmbossedLeatherPants.RequiredLevel.set(3)
export let AzureSilkGloves = std.Items.create(MODNAME,'azuresilkgloves',4319)
AzureSilkGloves.Quality.setGreen()
AzureSilkGloves.RequiredLevel.set(3)
export let AzureSilkVest = std.Items.create(MODNAME,'azuresilkvest',4324)
AzureSilkVest.Quality.setGreen()
AzureSilkVest.RequiredLevel.set(3)
export let AzureSilkPants = std.Items.create(MODNAME,'azuresilkpants',7046)
AzureSilkPants.Quality.setGreen()
AzureSilkPants.RequiredLevel.set(3)
export let AzureSilkHood = std.Items.create(MODNAME,'azuresilkhood',7048)
AzureSilkHood.Quality.setGreen()
AzureSilkHood.RequiredLevel.set(3)
export let AzureSilkBelt = std.Items.create(MODNAME,'azuresilkbelt',7052)
AzureSilkBelt.Quality.setGreen()
AzureSilkBelt.RequiredLevel.set(3)
export let AzureSilkCloak = std.Items.create(MODNAME,'azuresilkcloak',7053)
AzureSilkCloak.Quality.setGreen()
AzureSilkCloak.RequiredLevel.set(3)
export let CrimsonSilkBelt = std.Items.create(MODNAME,'crimsonsilkbelt',7055)
CrimsonSilkBelt.Quality.setGreen()
CrimsonSilkBelt.RequiredLevel.set(3)
export let CrimsonSilkCloak = std.Items.create(MODNAME,'crimsonsilkcloak',7056)
CrimsonSilkCloak.Quality.setGreen()
CrimsonSilkCloak.RequiredLevel.set(3)
export let CrimsonSilkVest = std.Items.create(MODNAME,'crimsonsilkvest',7058)
CrimsonSilkVest.Quality.setGreen()
CrimsonSilkVest.RequiredLevel.set(3)
export let CrimsonSilkShoulders = std.Items.create(MODNAME,'crimsonsilkshoulders',7059)
CrimsonSilkShoulders.Quality.setGreen()
CrimsonSilkShoulders.RequiredLevel.set(3)
export let CrimsonSilkPantaloons = std.Items.create(MODNAME,'crimsonsilkpantaloons',7062)
CrimsonSilkPantaloons.Quality.setGreen()
CrimsonSilkPantaloons.RequiredLevel.set(3)
export let CrimsonSilkRobe = std.Items.create(MODNAME,'crimsonsilkrobe',7063)
CrimsonSilkRobe.Quality.setGreen()
CrimsonSilkRobe.RequiredLevel.set(3)
export let CrimsonSilkGloves = std.Items.create(MODNAME,'crimsonsilkgloves',7064)
CrimsonSilkGloves.Quality.setGreen()
CrimsonSilkGloves.RequiredLevel.set(3)
export let SilveredBronzeBreastplate = std.Items.create(MODNAME,'silveredbronzebreastplate',2869)
SilveredBronzeBreastplate.Quality.setGreen()
SilveredBronzeBreastplate.RequiredLevel.set(3)
export let SilveredBronzeShoulders = std.Items.create(MODNAME,'silveredBronzeshoulders',3481)
SilveredBronzeShoulders.Quality.setGreen()
SilveredBronzeShoulders.RequiredLevel.set(3)
export let SilveredBronzeBoots = std.Items.create(MODNAME,'silveredbronzeboots',3482)
SilveredBronzeBoots.Quality.setGreen()
SilveredBronzeBoots.RequiredLevel.set(3)
export let SilveredBronzeGauntlets = std.Items.create(MODNAME,'silveredbronzegauntlets',3483)
SilveredBronzeGauntlets.Quality.setGreen()
SilveredBronzeGauntlets.RequiredLevel.set(3)
export let BarbaricIronShoulders = std.Items.create(MODNAME,'barbaricironshoulders',7913)
BarbaricIronShoulders.Quality.setGreen()
BarbaricIronShoulders.RequiredLevel.set(3)
export let BarbaricIronBreastplate = std.Items.create(MODNAME,'barbaricironbreastplate',7914)
BarbaricIronBreastplate.Quality.setGreen()
BarbaricIronBreastplate.RequiredLevel.set(3)
export let BarbaricIronHelm = std.Items.create(MODNAME,'barbaricironhelm',7915)
BarbaricIronHelm.Quality.setGreen()
BarbaricIronHelm.RequiredLevel.set(3)
export let BarbaricIronBoots = std.Items.create(MODNAME,'barbaricironboots',7916)
BarbaricIronBoots.Quality.setGreen()
BarbaricIronBoots.RequiredLevel.set(3)
export let BarbaricIronGloves = std.Items.create(MODNAME,'barbaricirongloves',7917)
BarbaricIronGloves.Quality.setGreen()
BarbaricIronGloves.RequiredLevel.set(3)

export let MinorManaPotion = std.Items.create(MODNAME,'minormanapotion',2455)
MinorManaPotion.Quality.setWhite()
export let MinorHealingPotion = std.Items.create(MODNAME,'minorhealingpotion',118)
MinorHealingPotion.Quality.setWhite()
export let MinorRejuvenationPotion = std.Items.create(MODNAME,'minorrejuvenationpotion',2456)
MinorRejuvenationPotion.Quality.setWhite()
export let DiscoloredHealingPotion = std.Items.create(MODNAME,'discoloredhealingpotion',4596)
DiscoloredHealingPotion.Quality.setWhite()
export let LesserHealingPotion = std.Items.create(MODNAME,'lesserhealingpotion',858)
LesserHealingPotion.Quality.setWhite()
export let SwiftnessPotion = std.Items.create(MODNAME,'swiftnesspotion',2459)
SwiftnessPotion.Quality.setWhite()
export let RagePotion = std.Items.create(MODNAME,'ragepotion',5631)
RagePotion.Quality.setWhite()
export let SwimSpeedPotion = std.Items.create(MODNAME,'swimspeedpotion',6372)
SwimSpeedPotion.Quality.setWhite()
export let LesserManaPotion = std.Items.create(MODNAME,'lessermanapotion',3385)
LesserManaPotion.Quality.setWhite()

export let ScrollofSpiritVIII = std.Items.create(MODNAME,'scrollofspiritviii',43465)
ScrollofSpiritVIII.Name.enGB.set('Scroll of Spirit')
ScrollofSpiritVIII.Quality.setWhite()
ScrollofSpiritVIII.Spells.clear(0)
ScrollofSpiritVIII.Spells.add(SpiritI.ID,undefined,undefined,-1)
ScrollofSpiritVIII.RequiredLevel.set(0)
export let ScrollofProtectionVIII = std.Items.create(MODNAME,'scrollofprotectionviii',43465)
ScrollofProtectionVIII.Name.enGB.set('Scroll of Protection')
ScrollofProtectionVIII.Quality.setWhite()
ScrollofProtectionVIII.Spells.clear(0)
ScrollofProtectionVIII.Spells.add(ProtectionI.ID,undefined,undefined,-1)
ScrollofProtectionVIII.RequiredLevel.set(0)
export let ScrollofAgilityVIII = std.Items.create(MODNAME,'scrollofagilityviii',43465)
ScrollofAgilityVIII.Name.enGB.set('Scroll of Agility')
ScrollofAgilityVIII.Quality.setWhite()
ScrollofAgilityVIII.Spells.clear(0)
ScrollofAgilityVIII.Spells.add(AgilityI.ID,undefined,undefined,-1)
ScrollofAgilityVIII.RequiredLevel.set(0)
export let ScrollofIntellectVIII = std.Items.create(MODNAME,'scrollofintellectviii',43465)
ScrollofIntellectVIII.Name.enGB.set('Scroll of Intellect')
ScrollofIntellectVIII.Quality.setWhite()
ScrollofIntellectVIII.Spells.clear(0)
ScrollofIntellectVIII.Spells.add(IntellectI.ID,undefined,undefined,-1)
ScrollofIntellectVIII.RequiredLevel.set(0)
export let ScrollofStaminaVIII = std.Items.create(MODNAME,'scrollofstaminaviii',43465)
ScrollofStaminaVIII.Name.enGB.set('Scroll of Stamina')
ScrollofStaminaVIII.Quality.setWhite()
ScrollofStaminaVIII.Spells.clear(0)
ScrollofStaminaVIII.Spells.add(StaminaI.ID,undefined,undefined,-1)
ScrollofStaminaVIII.RequiredLevel.set(0)
export let ScrollofStrengthVIII = std.Items.create(MODNAME,'scrollofstrengthviii',43465)
ScrollofStrengthVIII.Name.enGB.set('Scroll of Strength')
ScrollofStrengthVIII.Quality.setWhite()
ScrollofStrengthVIII.Spells.clear(0)
ScrollofStrengthVIII.Spells.add(StrengthI.ID,undefined,undefined,-1)
ScrollofStrengthVIII.RequiredLevel.set(0)