import { std } from "tswow-stdlib"
import { MODNAME } from "../modname"

export let IncreasedHealth1 = std.Spells.create(MODNAME,'increasedhealth1-spell',34747)
IncreasedHealth1.Name.enGB.set('Invincible')
IncreasedHealth1.Description.enGB.set('Total Health increased by $s1%.')
IncreasedHealth1.Effects.get(0).Aura.MOD_INCREASE_HEALTH_PERCENT.set()
IncreasedHealth1.Effects.get(0).BasePoints.set(1)
IncreasedHealth1.Effects.get(0).BasePoints.set(0)
IncreasedHealth1.Effects.get(1).Aura.NONE.set()
IncreasedHealth1.Effects.get(2).Aura.NONE.set()
IncreasedHealth1.Duration.set(-1)
IncreasedHealth1.Attributes.REACTIVATE_AT_RESURRECT.set(1)
IncreasedHealth1.Attributes.CANT_BE_CANCELED.set(1)
IncreasedHealth1.Attributes.HIDE_FROM_AURA_BAR.set(0)
IncreasedHealth1.Stacks.set(99)

export let IncreasedDamage1 = std.Spells.create(MODNAME,'increaseddamage1-spell',34747)
IncreasedDamage1.Name.enGB.set('Hardened')
IncreasedDamage1.Description.enGB.set('Total Damage dealt increased by $s1%.')
IncreasedDamage1.Effects.get(0).Aura.MOD_DAMAGE_PERCENT_DONE.set()
IncreasedDamage1.Effects.get(0).BasePoints.set(1)
IncreasedDamage1.Effects.get(0).BasePoints.set(0)
IncreasedDamage1.Effects.get(1).Aura.NONE.set()
IncreasedDamage1.Effects.get(2).Aura.NONE.set()
IncreasedDamage1.Duration.set(-1)
IncreasedDamage1.Attributes.REACTIVATE_AT_RESURRECT.set(1)
IncreasedDamage1.Attributes.CANT_BE_CANCELED.set(1)
IncreasedDamage1.Attributes.HIDE_FROM_AURA_BAR.set(0)
IncreasedDamage1.Stacks.set(99)

export let IncreasedSpellpower1 = std.Spells.create(MODNAME,'increasedsp1-spell',34747)
IncreasedSpellpower1.Name.enGB.set('Spellbender')
IncreasedSpellpower1.Description.enGB.set('Total Spell Power increased by $s1%.')
IncreasedSpellpower1.Effects.get(0).Aura.MOD_HEALING_DONE_PERCENT.set()
IncreasedSpellpower1.Effects.get(0).BasePoints.set(1)
IncreasedSpellpower1.Effects.get(0).BasePoints.set(0)
IncreasedSpellpower1.Effects.get(1).Aura.MOD_SPELL_DAMAGE_OF_STAT_PERCENT.set()
IncreasedSpellpower1.Effects.get(1).BasePoints.set(1)
IncreasedSpellpower1.Effects.get(1).BasePoints.set(0)
IncreasedSpellpower1.Effects.get(1).MiscValueA.set(126)
IncreasedSpellpower1.Effects.get(1).MiscValueB.set(3)
IncreasedSpellpower1.Effects.get(2).Aura.NONE.set()
IncreasedSpellpower1.Duration.set(-1)
IncreasedSpellpower1.Attributes.REACTIVATE_AT_RESURRECT.set(1)
IncreasedSpellpower1.Attributes.CANT_BE_CANCELED.set(1)
IncreasedSpellpower1.Attributes.HIDE_FROM_AURA_BAR.set(0)
IncreasedSpellpower1.Stacks.set(99)

export let IncreasedAttackpower1 = std.Spells.create(MODNAME,'increasedap1-spell',34747)
IncreasedAttackpower1.Name.enGB.set('Warlord')
IncreasedAttackpower1.Description.enGB.set('Total Attack Power increased by $s1%.')
IncreasedAttackpower1.Effects.get(0).Aura.MOD_ATTACK_POWER_PCT.set()
IncreasedAttackpower1.Effects.get(0).BasePoints.set(1)
IncreasedAttackpower1.Effects.get(0).BasePoints.set(0)
IncreasedAttackpower1.Effects.get(1).Aura.NONE.set()
IncreasedAttackpower1.Effects.get(2).Aura.NONE.set()
IncreasedAttackpower1.Duration.set(-1)
IncreasedAttackpower1.Attributes.REACTIVATE_AT_RESURRECT.set(1)
IncreasedAttackpower1.Attributes.CANT_BE_CANCELED.set(1)
IncreasedAttackpower1.Attributes.HIDE_FROM_AURA_BAR.set(0)
IncreasedAttackpower1.Stacks.set(99)

