export namespace ID {
    export const TESTER_MOD_STARTQUEST1_DRAFTPAPER : uint32 = GetID("item_template","tester-mod","startQuest1-draftpaper");
    export const TESTER_MOD_STARTQUEST2_EMPTYVIALS : uint32 = GetID("item_template","tester-mod","startQuest2-emptyVials");
    export const TESTER_MOD_STARTQUEST2_BLANKPAPERS : uint32 = GetID("item_template","tester-mod","startquest2-blankpapers");
    export const TESTER_MOD_STARTQUEST3_MYSTERIOUSLIQUIDVIAL : uint32 = GetID("item_template","tester-mod","startQuest3-mysteriousliquidvial");
    export const TESTER_MOD_STARTQUEST3_POORNOTES : uint32 = GetID("item_template","tester-mod","startquest3-poornotes");
    export const TESTER_MOD_STARTQUEST4_PLAGUEPAPERS : uint32 = GetID("item_template","tester-mod","startquest4-plaguepapers");
    export const TESTER_MOD_STARTQUEST5_SIGNEDDOC : uint32 = GetID("item_template","tester-mod","startquest5-signeddoc");
    export const TESTER_MOD_SKILLSHOT_PROC : uint32 = GetID("Spell","tester-mod","skillshot-proc");
    export const TESTER_MOD_SKILLSHOT_CAST : uint32 = GetID("Spell","tester-mod","skillshot-cast");
    export const TESTER_MOD_SKILLSHOT_CREATURE : uint32 = GetID("creature_template","tester-mod","skillshot-creature");
    export const TESTER_MOD_STARTQUEST1 : uint32 = GetID("quest_template","tester-mod","startQuest1");
    export const TESTER_MOD_STARTQUEST2 : uint32 = GetID("quest_template","tester-mod","startQuest2");
    export const TESTER_MOD_STARTQUEST3 : uint32 = GetID("quest_template","tester-mod","startQuest3");
    export const TESTER_MOD_STARTQUEST4 : uint32 = GetID("quest_template","tester-mod","startQuest4");
    export const TESTER_MOD_STARTQUEST5 : uint32 = GetID("quest_template","tester-mod","startQuest5");
    export const TESTER_MOD_BUTTONIDMESSAGE : uint32 = GetID("Messages","tester-mod","buttonIDMessage");
    export const TESTER_MOD_SHOWFRAMEMESSAGE : uint32 = GetID("Messages","tester-mod","showFrameMessage");
    export const TESTER_MOD_ITEMMESSAGE : uint32 = GetID("Messages","tester-mod","itemMessage");
    export const TESTER_MOD_CURRENCYMESSAGE : uint32 = GetID("Messages","tester-mod","currencyMessage");
};